# Task 2: Model monitoring

In this notebook, you monitor and evaluate the data captured from the endpoint. You create a baseline with which you compare the real-time traffic. Once a baseline is ready, you set up a schedule to continuously evaluate and compare the data against the baseline.

## Task 2.1: Environment setup

In this task, you set up your environment.

In [1]:
#install-dependencies
%pip install "sagemaker>=2,<3"
%matplotlib inline
from datetime import datetime, timedelta
import json
import boto3
import time
import pandas as pd
import matplotlib.pyplot as plt
from sagemaker import get_execution_role, session
from sagemaker.s3 import S3Uploader
from sagemaker.image_uris import retrieve
from sagemaker.predictor import Predictor
from sagemaker.serializers import CSVSerializer
from sagemaker.deserializers import CSVDeserializer
from time import sleep
from sagemaker.model_monitor import DefaultModelMonitor
from sagemaker.model_monitor.dataset_format import DatasetFormat
from sagemaker.model_monitor import CronExpressionGenerator

region = boto3.Session().region_name
role = get_execution_role()
sm_session = session.Session(boto3.Session())
sm = boto3.Session().client("sagemaker")
sm_runtime = boto3.Session().client("sagemaker-runtime")
cw = boto3.Session().client("cloudwatch")

#repo_path = './'
bucket = sm_session.default_bucket()
prefix = 'sagemaker/abalone'
data_capture_prefix = "{}/datacapture".format(prefix)
s3_capture_upload_path = "s3://{}/{}".format(bucket, data_capture_prefix)
capture_modes = [ "Input",  "Output" ]
code_prefix = "{}/code".format(prefix)
s3_code_preprocessor_uri = "s3://{}/{}/{}".format(bucket, code_prefix, "preprocessor.py")
s3_code_postprocessor_uri = "s3://{}/{}/{}".format(bucket, code_prefix, "postprocessor.py")
reports_prefix = "{}/reports".format(prefix)
s3_report_path = "s3://{}/{}".format(bucket, reports_prefix)

import os

# This looks for the 'models' folder in your current location or one level up/down
# to dynamically find the correct repo_path
current_dir = os.getcwd()

if not os.path.exists(os.path.join(current_dir, "models")):
    # Try to find the notebook's actual directory if the kernel is lost in root
    # In Jupyter, this usually resolves the folder containing the .ipynb
    repo_path = os.path.abspath('') 
    
    # If we are still in root, we force it to the notebook's path
    if repo_path == '/home/sagemaker-user':
        # This is a safe 'hack' to find the folder without hardcoding 'Lab5Repository'
        # It finds the first directory containing 'models'
        for root, dirs, files in os.walk('/home/sagemaker-user'):
            if 'models' in dirs and 'lab_7.ipynb' in files:
                repo_path = root
                break
else:
    repo_path = current_dir

print(f"Verified Repo Path: {repo_path}")

Collecting sagemaker<3,>=2

  Downloading sagemaker-2.257.3-py3-none-any.whl.metadata (17 kB)

Collecting attrs<26,>=24 (from sagemaker<3,>=2)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: boto3<2.0,>=1.42.2 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (1.42.97)
Requirement already satisfied: cloudpickle>=2.2.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (3.1.2)
Requirement already satisfied: docker in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (7.1.0)
Requirement already satisfied: fastapi in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (0.136.1)
Requirement already satisfied: google-pasta in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (0.2.0)
Requirement already satisfied: graphene<4,>=3 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (3.4.3)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (6.10.0)
Requirement already satisfied: jsonschema in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (4.23.0)
Requirement already satisfied: numpy<3.0,>=1.26.4 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (1.26.4)
Requirement already satisfied: omegaconf<3,>=2.2 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (2.3.0)

Collecting packaging<25,>=23.0 (from sagemaker<3,>=2)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: pandas>=2.3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (2.3.3)

Collecting pathos (from sagemaker<3,>=2)
  Downloading pathos-0.3.5-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: platformdirs in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (4.9.6)
Requirement already satisfied: protobuf<7.0,>=3.12 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (6.31.1)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (5.9.8)
Requirement already satisfied: pyyaml>=6.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (6.0.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (2.34.2)

Collecting sagemaker-core<2.0.0,>=1.0.71 (from sagemaker<3,>=2)
  Downloading sagemaker_core-1.0.78-py3-none-any.whl.metadata (4.9 kB)

Requirement already satisfied: schema in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (0.7.7)
Requirement already satisfied: smdebug-rulesconfig==1.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (1.0.1)
Requirement already satisfied: tblib<4,>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (3.2.2)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (4.67.3)
Requirement already satisfied: urllib3<3.0.0,>=1.26.8 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (1.26.20)
Requirement already satisfied: uvicorn in /opt/conda/lib/python3.12/site-packages (from sagemaker<3,>=2) (0.46.0)
Requirement already satisfied: botocore<1.43.0,>=1.42.97 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker<3,>=2) (1.42.97)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker<3,>=2) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker<3,>=2) (0.16.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.12/site-packages (from botocore<1.43.0,>=1.42.97->boto3<2.0,>=1.42.2->sagemaker<3,>=2) (2.9.0.post0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker<3,>=2) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker<3,>=2) (3.2.0)
Requirement already satisfied: typing-extensions<5,>=4.7.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker<3,>=2) (4.15.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.12/site-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker<3,>=2) (4.1.0)

Requirement already satisfied: antlr4-python3-runtime==4.9.* in /opt/conda/lib/python3.12/site-packages (from omegaconf<3,>=2.2->sagemaker<3,>=2) (4.9.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.97->boto3<2.0,>=1.42.2->sagemaker<3,>=2) (1.17.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2) (2.13.4)
Requirement already satisfied: rich<15.0.0,>=13.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2) (14.3.4)
Requirement already satisfied: mock<5.0,>4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2) (4.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.12/site-packages (from jsonschema->sagemaker<3,>=2) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.12/site-packages (from jsonschema->sagemaker<3,>=2) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from jsonschema->sagemaker<3,>=2) (0.27.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2) (0.7.0)

Requirement already satisfied: pydantic-core==2.46.4 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2) (0.1.2)

Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas>=2.3.0->sagemaker<3,>=2) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=2.3.0->sagemaker<3,>=2) (2026.2)

Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests->sagemaker<3,>=2) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests->sagemaker<3,>=2) (3.15)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.12/site-packages (from requests->sagemaker<3,>=2) (2026.5.20)
Requirement already satisfied: starlette>=0.46.0 in /opt/conda/lib/python3.12/site-packages (from fastapi->sagemaker<3,>=2) (1.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from fastapi->sagemaker<3,>=2) (0.0.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /opt/conda/lib/python3.12/site-packages (from starlette>=0.46.0->fastapi->sagemaker<3,>=2) (4.13.0)

Collecting ppft>=1.7.8 (from pathos->sagemaker<3,>=2)
  Downloading ppft-1.7.8-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: dill>=0.4.1 in /opt/conda/lib/python3.12/site-packages (from pathos->sagemaker<3,>=2) (0.4.1)
Collecting pox>=0.3.7 (from pathos->sagemaker<3,>=2)

  Downloading pox-0.3.7-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: multiprocess>=0.70.19 in /opt/conda/lib/python3.12/site-packages (from pathos->sagemaker<3,>=2) (0.70.19)

Requirement already satisfied: click>=7.0 in /opt/conda/lib/python3.12/site-packages (from uvicorn->sagemaker<3,>=2) (8.2.1)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.12/site-packages (from uvicorn->sagemaker<3,>=2) (0.16.0)
Downloading sagemaker-2.257.3-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/1.7 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 35.5 MB/s  0:00:00

Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading packaging-24.2-py3-none-any.whl (65 kB)
Downloading sagemaker_core-1.0.78-py3-none-any.whl (444 kB)

Downloading pathos-0.3.5-py3-none-any.whl (82 kB)
Downloading pox-0.3.7-py3-none-any.whl (29 kB)

Downloading ppft-1.7.8-py3-none-any.whl (56 kB)

Installing collected packages: ppft, pox, packaging, attrs, pathos, sagemaker-core, sagemaker

  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0

   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/7 [packaging]

  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/7 [packaging]

   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━ 4/7 [pathos]

  Attempting uninstall: sagemaker-core
    Found existing installation: sagemaker-core 2.12.0
   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━ 4/7 [pathos]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 5/7 [sagemaker-core]

    Uninstalling sagemaker-core-2.12.0:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 5/7 [sagemaker-core]

      Successfully uninstalled sagemaker-core-2.12.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 5/7 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 5/7 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 5/7 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 5/7 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [sagemaker]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autogluon-multimodal 1.5.0 requires nvidia-ml-py3<8.0,>=7.352.0, which is not installed.
autogluon-timeseries 1.5.0 requires chronos-forecasting<2.4,>=2.2.2, which is not installed.
autogluon-timeseries 1.5.0 requires einops<1,>=0.7, which is not installed.
autogluon-timeseries 1.5.0 requires peft<0.18,>=0.13.0, which is not installed.
skops 0.14.0 requires prettytable>=3.9, which is not installed.
autogluon-multimodal 1.5.0 requires fsspec[http]<=2025.3, but you have fsspec 2026.3.0 which is incompatible.
sagemaker-mlops 1.11.0 requires sagemaker-core>=2.11.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-serve 1.11.0 requires sagemaker-core>=2.11.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-studio-analytics-extension 0.3.0 requires sparkmagic==0.22.0, but you have sparkmagic 0.21.0 which is incompatible.
sagemaker-train 1.11.0 requires sagemaker-core>=2.11.0, but you have sagemaker-core 1.0.78 which is incompatible.
sparkmagic 0.21.0 requires pandas<2.0.0,>=0.17.1, but you have pandas 2.3.3 which is incompatible.

Successfully installed attrs-25.4.0 packaging-24.2 pathos-0.3.5 pox-0.3.7 ppft-1.7.8 sagemaker-2.257.3 sagemaker-core-1.0.78

Note: you may need to restart the kernel to use updated packages.

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml

sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml

Verified Repo Path: /home/sagemaker-user/Lab7Repository/en_us

<i aria-hidden="true" class="fas fa-sticky-note" style="color:#563377"></i> **Note:** You may ignore any warnings after running the above cell and thoroughout subsequent cells.

## Task 2.2: Create a production endpoint with Data Capture enabled

To log the inputs to your endpoint and the inference outputs from your deployed model to Amazon S3, you can enable an Amazon SageMaker AI feature called Data Capture. Data Capture records information that can be used for training, debugging, and monitoring. SageMaker AI Model Monitor automatically parses this captured data and compares metrics from this data with a baseline that you create for the model.

In this task, you upload the pre-trained model to the S3 bucket, create an Sagemaker AI model object, configure a SageMaker AI real-time endpoint with Data Capture enabled, and create the real-time endpoint.

<i class="fas fa-sticky-note" style="color:#563377"></i> **Note:** Endpoint creation takes approximately 5 minutes to complete.

In [2]:
#create-production-endpoint
# Upload models
model_url = S3Uploader.upload(
    local_path=f"{repo_path}/models/model.tar.gz", desired_s3_uri=f"s3://{bucket}/{prefix}"
)

# Create the model definitions
model_name = f"abalone-A-{datetime.now():%Y-%m-%d-%H-%M-%S}"
image_uri = retrieve("xgboost", boto3.Session().region_name, "1.5-1")

# Create production model object
predictor=sm_session.create_model(
    name=model_name, role=role, container_defs={"Image": image_uri, "ModelDataUrl": model_url}
)

# Create the endpoint configurations
variant_name = 'AllTraffic'

endpoint_config_name = f'Abalone-Endpoint-1-{datetime.now():%Y-%m-%d-%H-%M-%S}'
endpoint_config_response = sm.create_endpoint_config(
    EndpointConfigName = endpoint_config_name,
    ProductionVariants=[
        {
            'ModelName':model_name,
            'InstanceType':'ml.m5.xlarge',
            'InitialInstanceCount':1,
            'VariantName':variant_name
        }
    ],
    
        DataCaptureConfig= {
        'EnableCapture': True, # Whether data should be captured or not.
        'InitialSamplingPercentage' : 100,
        'CaptureContentTypeHeader': {'CsvContentTypes': [ 'text/csv' ]},
        'DestinationS3Uri': s3_capture_upload_path,
        'CaptureOptions': [{"CaptureMode" : capture_mode} for capture_mode in capture_modes] # Example - Use list comprehension to capture both Input and Output
    }
)
print(f"Created the Production Model Endpoint Config: {endpoint_config_name}")
time.sleep(5)

# Create the endpoint with the production model
endpoint_name = f"Abalone-{datetime.now():%Y-%m-%d-%H-%M-%S}"
endpoint_response = sm.create_endpoint(EndpointName=endpoint_name, EndpointConfigName=endpoint_config_name)

def wait_for_endpoint_creation_complete(endpoint):
    """Helper function to wait for the completion of creating an endpoint"""
    response = sm.describe_endpoint(EndpointName=endpoint_name)
    status = response.get("EndpointStatus")
    while status == "Creating":
        print("Waiting for Endpoint Creation")
        time.sleep(15)
        response = sm.describe_endpoint(EndpointName=endpoint_name)
        status = response.get("EndpointStatus")

    if status != "InService":
        print(f"Failed to create endpoint, response: {response}")
        failureReason = response.get("FailureReason", "")
        raise SystemExit(
            f"Failed to create endpoint {endpoint_response['EndpointArn']}, status: {status}, reason: {failureReason}"
        )
    print(f"Endpoint {endpoint_response['EndpointArn']} successfully created.")

wait_for_endpoint_creation_complete(endpoint=endpoint_response)

Created the Production Model Endpoint Config: Abalone-Endpoint-1-2026-06-12-10-28-33

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Waiting for Endpoint Creation

Endpoint arn:aws:sagemaker:us-west-2:105806319240:endpoint/Abalone-2026-06-12-10-28-38 successfully created.

When the cell completes, an endpoint ARN is returned that looks like *arn:aws:sagemaker:us-west-2:012345678910:endpoint/abalone-2040-10-11-10-11-12*.

Your endpoint is currently configured with one variant, the production model. You can view the endpoint configuration using *describe_endpoint*.

In [3]:
#describe-the-endpoint
sm.describe_endpoint(EndpointName=endpoint_name)

{'EndpointName': 'Abalone-2026-06-12-10-28-38',
 'EndpointArn': 'arn:aws:sagemaker:us-west-2:105806319240:endpoint/Abalone-2026-06-12-10-28-38',
 'EndpointConfigName': 'Abalone-Endpoint-1-2026-06-12-10-28-33',
 'ProductionVariants': [{'VariantName': 'AllTraffic',
   'DeployedImages': [{'SpecifiedImage': '246618743249.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:1.5-1',
     'ResolvedImage': '246618743249.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost@sha256:cd128bd02824075bf2e02ee7923aaa8ab50f6c47a2d86d5747b78ca1c5199813',
     'ResolutionTime': datetime.datetime(2026, 6, 12, 10, 28, 40, 75000, tzinfo=tzlocal())}],
   'CurrentWeight': 1.0,
   'DesiredWeight': 1.0,
   'CurrentInstanceCount': 1,
   'DesiredInstanceCount': 1}],
 'DataCaptureConfig': {'EnableCapture': True,
  'CaptureStatus': 'Started',
  'CurrentSamplingPercentage': 100,
  'DestinationS3Uri': 's3://sagemaker-us-west-2-105806319240/sagemaker/abalone/datacapture'},
 'EndpointStatus': 'InService',
 'CreationTime': datetime.datetime(2026, 6, 12, 10, 28, 39, 381000, tzinfo=tzlocal()),
 'LastModifiedTime': datetime.datetime(2026, 6, 12, 10, 31, 44, 196000, tzinfo=tzlocal()),
 'ResponseMetadata': {'RequestId': '63810d69-41f2-4d13-a724-f0f7c58c1942',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '63810d69-41f2-4d13-a724-f0f7c58c1942',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '927',
   'date': 'Fri, 12 Jun 2026 10:32:13 GMT'},
  'RetryAttempts': 0}}

## Task 2.3: View the captured data

In this task, you invoke the endpoint created above using production data. Since you already enabled Data Capture on the endpoint, the request payload, response, and additional metadata is saved in the S3 location you specified earlier in the notebook. After invoking the endpoint, you examine the data captured in the S3 bucket.

First, use an initialized predictor configured with the endpoint name to invoke the endpoint. Invoking the endpoint with new records helps you confirm your Data Capture configuration is set up correctly. A predictor makes prediction requests to an Amazon SageMaker AI endpoint. Then, run inference by sending records to the endpoint.

In [4]:
#invoke-the-endpoint
predictor = Predictor(endpoint_name=endpoint_name,
                        serializer=CSVSerializer(),
                        deserializer=CSVDeserializer())

validate_dataset = "abalone_data_new_predictions.csv"

limit = 200  # Need at least 200 samples to compute standard deviations
i = 0
with open(f"{repo_path}/data/{validate_dataset}", "w") as validation_file:
    validation_file.write("prediction,label\n")  # CSV header
    with open(f"{repo_path}/data/abalone_data_new.csv", "r") as f:
        for row in f:
            (label, input_cols) = row.split(",", 1)
            prediction = predictor.predict(input_cols)[0][0]
            validation_file.write(f"{prediction},{label}\n")
            i += 1
            if i > limit:
                break
            print(".", end="", flush=True)
            sleep(0.5)

print("\nDone!")

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

Done!

Next, list the Data Capture files stored in Amazon S3.

In [5]:
#list-data-capture-files
s3_client = boto3.Session().client("s3")
current_endpoint_capture_prefix = "{}/{}".format(data_capture_prefix, endpoint_name)
result = s3_client.list_objects(Bucket=bucket, Prefix=current_endpoint_capture_prefix)
capture_files = [capture_file.get("Key") for capture_file in result.get("Contents")]
print("Found Capture Files:")
print("\n ".join(capture_files))

Found Capture Files:
sagemaker/abalone/datacapture/Abalone-2026-06-12-10-28-38/AllTraffic/2026/06/12/10/33-28-867-b7b86a39-1a5c-46b0-97dd-24f8da3dffc1.jsonl

Then, view the contents of a single Data Capture file. You should see all the data captured in a SageMaker AI specific JSON-line formatted file. Take a moment to review the first few lines in the captured file.

In [6]:
#view-captured-file-lines
def get_obj_body(obj_key):
    return s3_client.get_object(Bucket=bucket, Key=obj_key).get("Body").read().decode("utf-8")


capture_file = get_obj_body(capture_files[-1])
print(capture_file[:2000])

{"captureData":{"endpointInput":{"observedContentType":"text/csv","mode":"INPUT","data":"0.8421737350064652,0.8609915417351095,0.6888110025132029,0.7977896490322643,0.8196374991984011,0.8545097875688132,0.4648058399193789,0.0,0.0,1.0\n","encoding":"CSV"},"endpointOutput":{"observedContentType":"text/csv; charset=utf-8","mode":"OUTPUT","data":"10.524738311767578\n","encoding":"CSV"}},"eventMetadata":{"eventId":"1d6d8121-88a9-4056-813d-394c930ae538","inferenceTime":"2026-06-12T10:33:28Z"},"eventVersion":"0"}
{"captureData":{"endpointInput":{"observedContentType":"text/csv","mode":"INPUT","data":"1.403862929794872,1.523946529448224,1.6451766919530222,2.55695787544154,2.0651650715096967,2.736337747238168,2.1377931785031565,0.0,0.0,1.0\n","encoding":"CSV"},"endpointOutput":{"observedContentType":"text/csv; charset=utf-8","mode":"OUTPUT","data":"11.895867347717285\n","encoding":"CSV"}},"eventMetadata":{"eventId":"42b83fec-8032-48ec-b909-9e837af754ad","inferenceTime":"2026-06-12T10:33:29Z"},"eventVersion":"0"}
{"captureData":{"endpointInput":{"observedContentType":"text/csv","mode":"INPUT","data":"1.1878286241070237,0.9629846167678965,1.0986820122731253,1.4397317386693333,1.8080238952905905,1.315742130625028,0.8481987716781613,0.0,0.0,1.0\n","encoding":"CSV"},"endpointOutput":{"observedContentType":"text/csv; charset=utf-8","mode":"OUTPUT","data":"9.603405952453613\n","encoding":"CSV"}},"eventMetadata":{"eventId":"17c42523-ad99-487c-8b7f-65558e8f960c","inferenceTime":"2026-06-12T10:33:30Z"},"eventVersion":"0"}
{"captureData":{"endpointInput":{"observedContentType":"text/csv","mode":"INPUT","data":"0.9285874572816049,0.9629846167678965,1.2353056821930999,1.895469472177701,1.861594973669571,1.8000360908340534,0.8481987716781613,1.0,0.0,0.0\n","encoding":"CSV"},"endpointOutput":{"observedContentType":"text/csv; charset=utf-8","mode":"OUTPUT","data":"11.39594554901123\n","encoding":"CSV"}},"eventMetadata":{"eventId":"53703145-5b3e-4d5e-981a-007ec31637d2","inferenceTime":"2026-

Finally, view the contents of one captured endpoint input and output record.

In [7]:
#print-json-file
print(json.dumps(json.loads(capture_file.split("\n")[0]), indent=2))

{
  "captureData": {
    "endpointInput": {
      "observedContentType": "text/csv",
      "mode": "INPUT",
      "data": "0.8421737350064652,0.8609915417351095,0.6888110025132029,0.7977896490322643,0.8196374991984011,0.8545097875688132,0.4648058399193789,0.0,0.0,1.0\n",
      "encoding": "CSV"
    },
    "endpointOutput": {
      "observedContentType": "text/csv; charset=utf-8",
      "mode": "OUTPUT",
      "data": "10.524738311767578\n",
      "encoding": "CSV"
    }
  },
  "eventMetadata": {
    "eventId": "1d6d8121-88a9-4056-813d-394c930ae538",
    "inferenceTime": "2026-06-12T10:33:28Z"
  },
  "eventVersion": "0"
}

Enabling Data Capture on your endpoints gives you more flexibility when you want to save information for training, debugging, and monitoring. Since SageMaker AI Model Monitor parses this captured data automatically, using Data Capture helps you compare new records to baseline data. 

You have not configured a baseline yet. In the next task, you use SageMaker AI Model Monitor to generate baseline statistics and constraints.

## Task 2.4: Generate baseline statistics and constraints

In this task, you create a baseline. Baseline statistics and constraints serve as a standard for detecting data drift and other data quality issues. 

The test dataset from training the model is often a good baseline dataset. The test dataset schema and the inference dataset schema should exactly match, including the number and order of the features. From the test dataset, you can ask SageMaker AI to suggest a set of baseline constraints and generate descriptive statistics to explore the data.

First, configure the baseline prefixes and variables.

In [8]:
#configure-baseline-variables
baseline_prefix = prefix + "/baselining"
baseline_data_prefix = baseline_prefix + "/data"
baseline_results_prefix = baseline_prefix + "/results"

baseline_data_uri = "s3://{}/{}".format(bucket, baseline_data_prefix)
baseline_results_uri = "s3://{}/{}".format(bucket, baseline_results_prefix)
print("Baseline data uri: {}".format(baseline_data_uri))
print("Baseline results uri: {}".format(baseline_results_uri))

Baseline data uri: s3://sagemaker-us-west-2-105806319240/sagemaker/abalone/baselining/data
Baseline results uri: s3://sagemaker-us-west-2-105806319240/sagemaker/abalone/baselining/results

Next, start a job to suggest a baseline and constraints. *DefaultModelMonitor.suggest_baseline()* starts a **ProcessingJob** using a SageMaker AI provided Model Monitor container to generate the baseline and constraints.

<i class="fas fa-sticky-note" style="color:#563377"></i> **Note:** A baseline job takes approximately 10 minutes to complete.

<i class="fas fa-info-circle" style="color:#008296"></i> **Learn more:** Refer to [Create a Baseline](https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-create-baseline.html) for more information about creating baseline calculations of statistics and constraints.

In [9]:
#create-baselining-job
my_default_monitor = DefaultModelMonitor(
    role=role,
    instance_count=1,
    instance_type="ml.t3.xlarge",
    volume_size_in_gb=20,
    max_runtime_in_seconds=3600,
)

my_default_monitor.suggest_baseline(
    baseline_dataset=f"{repo_path}/data/abalone_data_new_withheader.csv",
    dataset_format=DatasetFormat.csv(header=True),
    output_s3_uri=baseline_results_uri,
    wait=True,
)

INFO:sagemaker:Creating processing-job with name baseline-suggestion-job-2026-06-12-10-35-42-126

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

2026-06-12 10:39:12.842916: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2026-06-12 10:39:12.842970: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2026-06-12 10:39:14.525633: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2026-06-12 10:39:14.525683: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2026-06-12 10:39:14.525710: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-10-0-203-147.us-west-2.compute.internal): /proc/driver/nvidia/version does not exist
2026-06-12 10:39:14.526019: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-06-12 10:39:15,957 - __main__ - INFO - All params:{'ProcessingJobArn': 'arn:aws:sagemaker:us-west-2:105806319240:processing-job/baseline-suggestion-job-2026-06-12-10-35-42-126', 'ProcessingJobName': 'baseline-suggestion-job-2026-06-12-10-35-42-126', 'Environment': {'dataset_format': '{"csv": {"header": true, "output_columns_position": "START"}}', 'dataset_source': '/opt/ml/processing/input/baseline_dataset_input', 'output_path': '/opt/ml/processing/output', 'publish_cloudwatch_metrics': 'Disabled'}, 'AppSpecification': {'ImageUri': '159807026194.dkr.ecr.us-west-2.amazonaws.com/sagemaker-model-monitor-analyzer', 'ContainerEntrypoint': None, 'ContainerArguments': None}, 'ProcessingInputs': [{'InputName': 'baseline_dataset_input', 'AppManaged': False, 'S3Input': {'LocalPath': '/opt/ml/processing/input/baseline_dataset_input', 'S3Uri': 's3://sagemaker-us-west-2-105806319240/model-monitor/baselining/baseline-suggestion-job-2026-06-12-10-35-42-126/input/baseline_dataset_input', 'S3DataDistributionType': 'FullyReplicated', 'S3DataType': 'S3Prefix', 'S3InputMode': 'File', 'S3CompressionType': 'None', 'S3DownloadMode': 'StartOfJob'}, 'DatasetDefinitionInput': None}], 'ProcessingOutputConfig': {'Outputs': [{'OutputName': 'monitoring_output', 'AppManaged': False, 'S3Output': {'LocalPath': '/opt/ml/processing/output', 'S3Uri': 's3://sagemaker-us-west-2-105806319240/sagemaker/abalone/baselining/results', 'S3UploadMode': 'EndOfJob'}, 'FeatureStoreOutput': None}], 'KmsKeyId': None}, 'ProcessingResources': {'ClusterConfig': {'InstanceCount': 1, 'InstanceType': 'ml.t3.xlarge', 'VolumeSizeInGB': 20, 'VolumeKmsKeyId': None}}, 'NetworkConfig': {'VpcConfig': None, 'EnableNetworkIsolation': False, 'EnableInterContainerTrafficEncryption': False}, 'RoleArn': 'arn:aws:iam::105806319240:role/LabVPC-notebook-role', 'StoppingCondition': {'MaxRuntimeInSeconds': 3600}}
2026-06-12 10:39:15,957 - __main__ - INFO - Current Environment:{'dataset_format': '{"csv": {"header": true, "output_columns_position": "START"}}', 'dataset_source': '/opt/ml/processing/input/baseline_dataset_input', 'output_path': '/opt/ml/processing/output', 'publish_cloudwatch_metrics': 'Disabled'}
2026-06-12 10:39:15,957 - __main__ - INFO - categorical_drift_method:None
2026-06-12 10:39:15,957 - DefaultDataAnalyzer - INFO - Performing analysis with input: {"dataset_source": "/opt/ml/processing/input/baseline_dataset_input", "dataset_format": {"csv": {"header": true, "output_columns_position": "START"}}, "output_path": "/opt/ml/processing/output", "monitoring_input_type": null, "analysis_type": null, "problem_type": null, "inference_attribute": null, "probability_attribute": null, "ground_truth_attribute": null, "probability_threshold_attribute": null, "positive_label": null, "exclude_features_attribute": null, "record_preprocessor_script": null, "post_analytics_processor_script": null, "baseline_constraints": null, "baseline_statistics": null, "data_quality_monitoring_config": {"evaluate_constraints": "Enabled", "emit_metrics": "Enabled", "datatype_check_threshold": 1.0, "domain_content_threshold": 1.0, "distribution_constraints": {"perform_comparison": "Enabled", "comparison_threshold": 0.1, "comparison_method": "Robust", "categorical_comparison_threshold": 0.1, "categorical_drift_method": "LInfinity"}}, "start_time": null, "end_time": null, "metric_time": null, "cloudwatch_metrics_directory": "/opt/ml/output/metrics/cloudwatch", "publish_cloudwatch_metrics": "Disabled", "sagemaker_endpoint_name": null, "sagemaker_monitoring_schedule_name": null, "output_message_file": "/opt/ml/output/message", "detect_outliers": null, "detect_drift": null, "image_data": null, "report_enabled": false, "auto_ml_job_detail": null}
2026-06-12 10:39:15,957 - DefaultDataAnalyzer - INFO - Bootstrapping yarn
2026-06-12 10:39:15,957 - bootstrap - INFO - Copy aws jars
2026-06-12 10:39:16,024 - bootstrap - INFO - Copy cluster config
2026-06-12 10:39:16,025 - bootstrap - INFO - Write runtime cluster config
2026-06-12 10:39:16,026 - bootstrap - INFO - Resource Config is: {'current_host': 'algo-1', 'current_instance_type': 'ml.t3.xlarge', 'current_group_name': 'homogeneousCluster', 'hosts': ['algo-1'], 'instance_groups': [{'instance_group_name': 'homogeneousCluster', 'instance_type': 'ml.t3.xlarge', 'hosts': ['algo-1']}], 'network_interface_name': 'eth0', 'topology': None}
2026-06-12 10:39:16,063 - bootstrap - INFO - Finished Yarn configuration files setup.
2026-06-12 10:39:16,063 - bootstrap - INFO - Starting spark process for master node algo-1
2026-06-12 10:39:16,063 - bootstrap - INFO - Running command: /usr/hadoop-3.0.0/bin/hdfs namenode -format -force
WARNING: /usr/hadoop-3.0.0/logs does not exist. Creating.
2026-06-12 10:39:16,653 INFO namenode.NameNode: STARTUP_MSG:
/************************************************************
STARTUP_MSG: Starting NameNode
STARTUP_MSG:   host = ip-10-0-203-147.us-west-2.compute.internal/10.0.203.147
STARTUP_MSG:   args = [-format, -force]
STARTUP_MSG:   version = 3.0.0

2026-06-12 10:39:19,814 - bootstrap - INFO - Failed to run /usr/hadoop-3.0.0/bin/hdfs --daemon start namenode, return code 1
2026-06-12 10:39:19,814 - bootstrap - INFO - Running command: /usr/hadoop-3.0.0/bin/hdfs --daemon start datanode
2026-06-12 10:39:21,930 - bootstrap - INFO - Failed to run /usr/hadoop-3.0.0/bin/hdfs --daemon start datanode, return code 1
2026-06-12 10:39:21,930 - bootstrap - INFO - Running command: /usr/hadoop-3.0.0/bin/yarn --daemon start resourcemanager
WARNING: YARN_LOG_DIR has been replaced by HADOOP_LOG_DIR. Using value of YARN_LOG_DIR.
WARNING: /var/log/yarn/ does not exist. Creating.
2026-06-12 10:39:24,055 - bootstrap - INFO - Failed to run /usr/hadoop-3.0.0/bin/yarn --daemon start resourcemanager, return code 1
2026-06-12 10:39:24,056 - bootstrap - INFO - Running command: /usr/hadoop-3.0.0/bin/yarn --daemon start nodemanager
WARNING: YARN_LOG_DIR has been replaced by HADOOP_LOG_DIR. Using value of YARN_LOG_DIR.
2026-06-12 10:39:26,209 - bootstrap - INFO - Failed to run /usr/hadoop-3.0.0/bin/yarn --daemon start nodemanager, return code 1
2026-06-12 10:39:26,210 - bootstrap - INFO - Running command: /usr/hadoop-3.0.0/bin/yarn --daemon start proxyserver
WARNING: YARN_LOG_DIR has been replaced by HADOOP_LOG_DIR. Using value of YARN_LOG_DIR.
2026-06-12 10:39:28,370 - bootstrap - INFO - Failed to run /usr/hadoop-3.0.0/bin/yarn --daemon start proxyserver, return code 1
2026-06-12 10:39:28,371 - DefaultDataAnalyzer - INFO - Total number of hosts in the cluster: 1

2026-06-12 10:39:38,376 - DefaultDataAnalyzer - INFO - Running command: bin/spark-submit --master yarn --deploy-mode client --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider --conf spark.serializer=org.apache.spark.serializer.KryoSerializer /opt/amazon/sagemaker-data-analyzer-1.0-jar-with-dependencies.jar --analytics_input /tmp/spark_job_config.json
2026-06-12 10:39:40,317 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2026-06-12 10:39:40,914 INFO Main: Start analyzing with args: --analytics_input /tmp/spark_job_config.json
2026-06-12 10:39:40,982 INFO Main: Analytics input path: DataAnalyzerParams(/tmp/spark_job_config.json,yarn)
2026-06-12 10:39:40,997 INFO FileUtil: Read file from path /tmp/spark_job_config.json.
2026-06-12 10:39:41,667 INFO spark.SparkContext: Running Spark version 3.3.0
2026-06-12 10:39:41,697 INFO resource.ResourceUtils: ==============================================================
2026-06-12 10:39:41,697 INFO resource.ResourceUtils: No custom resources configured for spark.driver.
2026-06-12 10:39:41,697 INFO resource.ResourceUtils: ==============================================================
2026-06-12 10:39:41,698 INFO spark.SparkContext: Submitted application: SageMakerDataAnalyzer
2026-06-12 10:39:41,727 INFO resource.ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 3, script: , vendor: , memory -> name: memory, amount: 11596, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
2026-06-12 10:39:41,743 INFO resource.ResourceProfile: Limiting resource is cpus at 3 tasks per executor
2026-06-12 10:39:41,745 INFO resource.ResourceProfileManager: Added ResourceProfile id: 0
2026-06-12 10:39:41,808 INFO spark.SecurityManager: Changing view acls to: root
2026-06-12 10:39:41,808 INFO spark.SecurityManager: Changing modify acls to: root
2026-06-12 10:39:41,808 INFO spark.SecurityManager: Changing view acls groups to:
2026-06-12 10:39:41,809 INFO spark.SecurityManager: Changing modify acls groups to:
2026-06-12 10:39:41,809 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
2026-06-12 10:39:42,245 INFO util.Utils: Successfully started service 'sparkDriver' on port 35605.
2026-06-12 10:39:42,285 INFO spark.SparkEnv: Registering MapOutputTracker
2026-06-12 10:39:42,331 INFO spark.SparkEnv: Registering BlockManagerMaster
2026-06-12 10:39:42,362 INFO storage.BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
2026-06-12 10:39:42,363 INFO storage.BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
2026-06-12 10:39:42,406 INFO spark.SparkEnv: Registering BlockManagerMasterHeartbeat
2026-06-12 10:39:42,448 INFO storage.DiskBlockManager: Created local directory at /tmp/blockmgr-ece27eed-73f1-4479-9b55-305ff3a27815
2026-06-12 10:39:42,476 INFO memory.MemoryStore: MemoryStore started with capacity 1458.6 MiB
2026-06-12 10:39:42,539 INFO spark.SparkEnv: Registering OutputCommitCoordinator
2026-06-12 10:39:42,593 INFO spark.SparkContext: Added JAR file:/opt/amazon/sagemaker-data-analyzer-1.0-jar-with-dependencies.jar at spark://10.0.203.147:35605/jars/sagemaker-data-analyzer-1.0-jar-with-dependencies.jar with timestamp 1781260781662

2026-06-12 10:39:43,284 INFO client.RMProxy: Connecting to ResourceManager at /10.0.203.147:8032
2026-06-12 10:39:44,254 INFO conf.Configuration: resource-types.xml not found
2026-06-12 10:39:44,254 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
2026-06-12 10:39:44,265 INFO yarn.Client: Verifying our application has not requested more than the maximum memory capability of the cluster (15814 MB per container)
2026-06-12 10:39:44,265 INFO yarn.Client: Will allocate AM container, with 896 MB memory including 384 MB overhead
2026-06-12 10:39:44,266 INFO yarn.Client: Setting up container launch context for our AM
2026-06-12 10:39:44,266 INFO yarn.Client: Setting up the launch environment for our AM container
2026-06-12 10:39:44,273 INFO yarn.Client: Preparing resources for our AM container
2026-06-12 10:39:44,372 WARN yarn.Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
2026-06-12 10:39:46,765 INFO yarn.Client: Uploading resource file:/tmp/spark-5e6ee794-d376-4f0a-bfbe-98f3a15f889f/__spark_libs__7131373908174709193.zip -> hdfs://10.0.203.147/user/root/.sparkStaging/application_1781260764017_0001/__spark_libs__7131373908174709193.zip
2026-06-12 10:39:48,259 INFO yarn.Client: Uploading resource file:/tmp/spark-5e6ee794-d376-4f0a-bfbe-98f3a15f889f/__spark_conf__2086533784036921989.zip -> hdfs://10.0.203.147/user/root/.sparkStaging/application_1781260764017_0001/__spark_conf__.zip
2026-06-12 10:39:48,716 INFO spark.SecurityManager: Changing view acls to: root
2026-06-12 10:39:48,716 INFO spark.SecurityManager: Changing modify acls to: root
2026-06-12 10:39:48,716 INFO spark.SecurityManager: Changing view acls groups to:
2026-06-12 10:39:48,716 INFO spark.SecurityManager: Changing modify acls groups to:
2026-06-12 10:39:48,717 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
2026-06-12 10:39:48,754 INFO yarn.Client: Submitting application application_1781260764017_0001 to ResourceManager
2026-06-12 10:39:49,024 INFO impl.YarnClientImpl: Submitted application application_1781260764017_0001
2026-06-12 10:39:50,030 INFO yarn.Client: Application report for application_1781260764017_0001 (state: ACCEPTED)
2026-06-12 10:39:50,035 INFO yarn.Client:
#011 client token: N/A
#011 diagnostics: [Fri Jun 12 10:39:49 +0000 2026] Scheduler has assigned a container for AM, waiting for AM container to be launched
#011 ApplicationMaster host: N/A
#011 ApplicationMaster RPC port: -1
#011 queue: default
#011 start time: 1781260788890
#011 final status: UNDEFINED
#011 tracking URL: http://algo-1:8088/proxy/application_1781260764017_0001/
#011 user: root
2026-06-12 10:39:51,039 INFO yarn.Client: Application report for application_1781260764017_0001 (state: ACCEPTED)
2026-06-12 10:39:52,042 INFO yarn.Client: Application report for application_1781260764017_0001 (state: ACCEPTED)

2026-06-12 10:39:53,046 INFO yarn.Client: Application report for application_1781260764017_0001 (state: ACCEPTED)
2026-06-12 10:39:54,051 INFO yarn.Client: Application report for application_1781260764017_0001 (state: ACCEPTED)
2026-06-12 10:39:55,055 INFO yarn.Client: Application report for application_1781260764017_0001 (state: ACCEPTED)
2026-06-12 10:39:55,699 INFO cluster.YarnClientSchedulerBackend: Add WebUI Filter. org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter, Map(PROXY_HOSTS -> algo-1, PROXY_URI_BASES -> http://algo-1:8088/proxy/application_1781260764017_0001), /proxy/application_1781260764017_0001
2026-06-12 10:39:56,060 INFO yarn.Client: Application report for application_1781260764017_0001 (state: RUNNING)
2026-06-12 10:39:56,068 INFO yarn.Client:
#011 client token: N/A
#011 diagnostics: N/A
#011 ApplicationMaster host: 10.0.203.147
#011 ApplicationMaster RPC port: -1
#011 queue: default
#011 start time: 1781260788890
#011 final status: UNDEFINED
#011 tracking URL: http://algo-1:8088/proxy/application_1781260764017_0001/
#011 user: root
2026-06-12 10:39:56,071 INFO cluster.YarnClientSchedulerBackend: Application application_1781260764017_0001 has started running.
2026-06-12 10:39:56,105 INFO util.Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34811.
2026-06-12 10:39:56,106 INFO netty.NettyBlockTransferService: Server created on 10.0.203.147:34811
2026-06-12 10:39:56,109 INFO storage.BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2026-06-12 10:39:56,133 INFO storage.BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.0.203.147, 34811, None)
2026-06-12 10:39:56,138 INFO storage.BlockManagerMasterEndpoint: Registering block manager 10.0.203.147:34811 with 1458.6 MiB RAM, BlockManagerId(driver, 10.0.203.147, 34811, None)
2026-06-12 10:39:56,142 INFO storage.BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.0.203.147, 34811, None)
2026-06-12 10:39:56,143 INFO storage.BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.0.203.147, 34811, None)
2026-06-12 10:39:56,330 INFO util.log: Logging initialized @17715ms to org.sparkproject.jetty.util.log.Slf4jLog
2026-06-12 10:39:57,622 INFO cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: ApplicationMaster registered as NettyRpcEndpointRef(spark-client://YarnAM)

2026-06-12 10:40:01,832 INFO cluster.YarnSchedulerBackend$YarnDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (10.0.203.147:48616) with ID 1,  ResourceProfileId 0
2026-06-12 10:40:02,110 INFO storage.BlockManagerMasterEndpoint: Registering block manager algo-1:36143 with 5.9 GiB RAM, BlockManagerId(1, algo-1, 36143, None)

2026-06-12 10:40:13,134 INFO cluster.YarnClientSchedulerBackend: SchedulerBackend is ready for scheduling beginning after waiting maxRegisteredResourcesWaitingTime: 30000000000(ns)
2026-06-12 10:40:13,399 WARN spark.SparkContext: Spark is not running in local mode, therefore the checkpoint directory must not be on the local filesystem. Directory '/tmp' appears to be on the local filesystem.
2026-06-12 10:40:13,517 INFO internal.SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
2026-06-12 10:40:13,530 INFO internal.SharedState: Warehouse path is 'file:/usr/spark-3.3.0/spark-warehouse'.
2026-06-12 10:40:14,777 INFO datasources.InMemoryFileIndex: It took 61 ms to list leaf files for 1 paths.
2026-06-12 10:40:14,986 INFO memory.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 416.9 KiB, free 1458.2 MiB)
2026-06-12 10:40:15,358 INFO memory.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 39.2 KiB, free 1458.2 MiB)
2026-06-12 10:40:15,362 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on 10.0.203.147:34811 (size: 39.2 KiB, free: 1458.6 MiB)
2026-06-12 10:40:15,369 INFO spark.SparkContext: Created broadcast 0 from csv at DatasetReader.scala:99
2026-06-12 10:40:15,862 INFO input.FileInputFormat: Total input files to process : 1
2026-06-12 10:40:15,865 INFO input.FileInputFormat: Total input files to process : 1
2026-06-12 10:40:15,872 INFO input.CombineFileInputFormat: DEBUG: Terminated node allocation with : CompletedNodes: 1, size left: 11672
2026-06-12 10:40:15,945 INFO spark.SparkContext: Starting job: csv at DatasetReader.scala:99
2026-06-12 10:40:15,965 INFO scheduler.DAGScheduler: Got job 0 (csv at DatasetReader.scala:99) with 1 output partitions
2026-06-12 10:40:15,966 INFO scheduler.DAGScheduler: Final stage: ResultStage 0 (csv at DatasetReader.scala:99)
2026-06-12 10:40:15,967 INFO scheduler.DAGScheduler: Parents of final stage: List()
2026-06-12 10:40:15,968 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:15,975 INFO scheduler.DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[2] at csv at DatasetReader.scala:99), which has no missing parents
2026-06-12 10:40:16,029 INFO memory.MemoryStore: Block broadcast_1 stored as values in memory (estimated size 7.3 KiB, free 1458.1 MiB)
2026-06-12 10:40:16,047 INFO memory.MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 4.2 KiB, free 1458.1 MiB)
2026-06-12 10:40:16,048 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on 10.0.203.147:34811 (size: 4.2 KiB, free: 1458.6 MiB)
2026-06-12 10:40:16,050 INFO spark.SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:16,073 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[2] at csv at DatasetReader.scala:99) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:16,074 INFO cluster.YarnScheduler: Adding task set 0.0 with 1 tasks resource profile 0
2026-06-12 10:40:16,136 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (algo-1, executor 1, partition 0, PROCESS_LOCAL, 4640 bytes) taskResourceAssignments Map()
2026-06-12 10:40:16,482 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on algo-1:36143 (size: 4.2 KiB, free: 5.9 GiB)
2026-06-12 10:40:17,513 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on algo-1:36143 (size: 39.2 KiB, free: 5.9 GiB)
2026-06-12 10:40:17,960 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1846 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:17,966 INFO cluster.YarnScheduler: Removed TaskSet 0.0, whose tasks have all completed, from pool
2026-06-12 10:40:17,977 INFO scheduler.DAGScheduler: ResultStage 0 (csv at DatasetReader.scala:99) finished in 1.973 s
2026-06-12 10:40:17,982 INFO scheduler.DAGScheduler: Job 0 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:17,982 INFO cluster.YarnScheduler: Killing all running tasks in stage 0: Stage finished
2026-06-12 10:40:17,985 INFO scheduler.DAGScheduler: Job 0 finished: csv at DatasetReader.scala:99, took 2.038685 s
2026-06-12 10:40:18,174 INFO storage.BlockManagerInfo: Removed broadcast_1_piece0 on 10.0.203.147:34811 in memory (size: 4.2 KiB, free: 1458.6 MiB)
2026-06-12 10:40:18,182 INFO storage.BlockManagerInfo: Removed broadcast_1_piece0 on algo-1:36143 in memory (size: 4.2 KiB, free: 5.9 GiB)
2026-06-12 10:40:18,204 INFO storage.BlockManagerInfo: Removed broadcast_0_piece0 on 10.0.203.147:34811 in memory (size: 39.2 KiB, free: 1458.6 MiB)
2026-06-12 10:40:18,216 INFO storage.BlockManagerInfo: Removed broadcast_0_piece0 on algo-1:36143 in memory (size: 39.2 KiB, free: 5.9 GiB)
2026-06-12 10:40:20,925 INFO datasources.FileSourceStrategy: Pushed Filters:
2026-06-12 10:40:20,927 INFO datasources.FileSourceStrategy: Post-Scan Filters:
2026-06-12 10:40:20,931 INFO datasources.FileSourceStrategy: Output Data Schema: struct<rings: string, length: string, diameter: string, height: string, whole_weight: string ... 9 more fields>
2026-06-12 10:40:21,162 INFO memory.MemoryStore: Block broadcast_2 stored as values in memory (estimated size 416.5 KiB, free 1458.2 MiB)
2026-06-12 10:40:21,176 INFO memory.MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 39.1 KiB, free 1458.2 MiB)
2026-06-12 10:40:21,177 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on 10.0.203.147:34811 (size: 39.1 KiB, free: 1458.6 MiB)
2026-06-12 10:40:21,179 INFO spark.SparkContext: Created broadcast 2 from head at DataAnalyzer.scala:124
2026-06-12 10:40:21,200 INFO execution.FileSourceScanExec: Planning scan with bin packing, max size: 4194304 bytes, open cost is considered as scanning 4194304 bytes.
2026-06-12 10:40:21,259 INFO spark.SparkContext: Starting job: head at DataAnalyzer.scala:124
2026-06-12 10:40:21,261 INFO scheduler.DAGScheduler: Got job 1 (head at DataAnalyzer.scala:124) with 1 output partitions
2026-06-12 10:40:21,261 INFO scheduler.DAGScheduler: Final stage: ResultStage 1 (head at DataAnalyzer.scala:124)
2026-06-12 10:40:21,261 INFO scheduler.DAGScheduler: Parents of final stage: List()
2026-06-12 10:40:21,265 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:21,267 INFO scheduler.DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[11] at head at DataAnalyzer.scala:124), which has no missing parents
2026-06-12 10:40:21,339 INFO memory.MemoryStore: Block broadcast_3 stored as values in memory (estimated size 16.8 KiB, free 1458.1 MiB)
2026-06-12 10:40:21,342 INFO memory.MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 8.0 KiB, free 1458.1 MiB)
2026-06-12 10:40:21,343 INFO storage.BlockManagerInfo: Added broadcast_3_piece0 in memory on 10.0.203.147:34811 (size: 8.0 KiB, free: 1458.6 MiB)
2026-06-12 10:40:21,344 INFO spark.SparkContext: Created broadcast 3 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:21,344 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 1 (MapPartitionsRDD[11] at head at DataAnalyzer.scala:124) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:21,345 INFO cluster.YarnScheduler: Adding task set 1.0 with 1 tasks resource profile 0
2026-06-12 10:40:21,350 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1) (algo-1, executor 1, partition 0, PROCESS_LOCAL, 4968 bytes) taskResourceAssignments Map()
2026-06-12 10:40:21,397 INFO storage.BlockManagerInfo: Added broadcast_3_piece0 in memory on algo-1:36143 (size: 8.0 KiB, free: 5.9 GiB)
2026-06-12 10:40:22,241 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on algo-1:36143 (size: 39.1 KiB, free: 5.9 GiB)
2026-06-12 10:40:22,362 INFO storage.BlockManagerInfo: Added rdd_7_0 in memory on algo-1:36143 (size: 13.0 KiB, free: 5.9 GiB)
2026-06-12 10:40:22,494 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 1147 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:22,494 INFO cluster.YarnScheduler: Removed TaskSet 1.0, whose tasks have all completed, from pool
2026-06-12 10:40:22,497 INFO scheduler.DAGScheduler: ResultStage 1 (head at DataAnalyzer.scala:124) finished in 1.226 s
2026-06-12 10:40:22,498 INFO scheduler.DAGScheduler: Job 1 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:22,498 INFO cluster.YarnScheduler: Killing all running tasks in stage 1: Stage finished
2026-06-12 10:40:22,498 INFO scheduler.DAGScheduler: Job 1 finished: head at DataAnalyzer.scala:124, took 1.238970 s
2026-06-12 10:40:22,808 INFO codegen.CodeGenerator: Code generated in 239.345432 ms

2026-06-12 10:40:23,580 INFO storage.BlockManagerInfo: Removed broadcast_3_piece0 on 10.0.203.147:34811 in memory (size: 8.0 KiB, free: 1458.6 MiB)
2026-06-12 10:40:23,603 INFO storage.BlockManagerInfo: Removed broadcast_3_piece0 on algo-1:36143 in memory (size: 8.0 KiB, free: 5.9 GiB)
2026-06-12 10:40:23,723 WARN util.package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
2026-06-12 10:40:23,922 INFO scheduler.DAGScheduler: Registering RDD 16 (collect at AnalysisRunner.scala:326) as input to shuffle 0
2026-06-12 10:40:23,929 INFO scheduler.DAGScheduler: Got map stage job 2 (collect at AnalysisRunner.scala:326) with 1 output partitions
2026-06-12 10:40:23,930 INFO scheduler.DAGScheduler: Final stage: ShuffleMapStage 2 (collect at AnalysisRunner.scala:326)
2026-06-12 10:40:23,931 INFO scheduler.DAGScheduler: Parents of final stage: List()
2026-06-12 10:40:23,934 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:23,939 INFO scheduler.DAGScheduler: Submitting ShuffleMapStage 2 (MapPartitionsRDD[16] at collect at AnalysisRunner.scala:326), which has no missing parents
2026-06-12 10:40:23,977 INFO memory.MemoryStore: Block broadcast_4 stored as values in memory (estimated size 113.9 KiB, free 1458.0 MiB)
2026-06-12 10:40:23,982 INFO memory.MemoryStore: Block broadcast_4_piece0 stored as bytes in memory (estimated size 34.8 KiB, free 1458.0 MiB)
2026-06-12 10:40:23,983 INFO storage.BlockManagerInfo: Added broadcast_4_piece0 in memory on 10.0.203.147:34811 (size: 34.8 KiB, free: 1458.5 MiB)
2026-06-12 10:40:23,986 INFO spark.SparkContext: Created broadcast 4 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:23,990 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 2 (MapPartitionsRDD[16] at collect at AnalysisRunner.scala:326) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:23,990 INFO cluster.YarnScheduler: Adding task set 2.0 with 1 tasks resource profile 0
2026-06-12 10:40:24,000 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 2.0 (TID 2) (algo-1, executor 1, partition 0, PROCESS_LOCAL, 4957 bytes) taskResourceAssignments Map()
2026-06-12 10:40:24,028 INFO storage.BlockManagerInfo: Added broadcast_4_piece0 in memory on algo-1:36143 (size: 34.8 KiB, free: 5.9 GiB)
2026-06-12 10:40:25,244 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 2.0 (TID 2) in 1246 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:25,245 INFO cluster.YarnScheduler: Removed TaskSet 2.0, whose tasks have all completed, from pool
2026-06-12 10:40:25,247 INFO scheduler.DAGScheduler: ShuffleMapStage 2 (collect at AnalysisRunner.scala:326) finished in 1.304 s
2026-06-12 10:40:25,248 INFO scheduler.DAGScheduler: looking for newly runnable stages
2026-06-12 10:40:25,248 INFO scheduler.DAGScheduler: running: Set()
2026-06-12 10:40:25,249 INFO scheduler.DAGScheduler: waiting: Set()
2026-06-12 10:40:25,249 INFO scheduler.DAGScheduler: failed: Set()
2026-06-12 10:40:25,334 INFO spark.SparkContext: Starting job: collect at AnalysisRunner.scala:326
2026-06-12 10:40:25,337 INFO scheduler.DAGScheduler: Got job 3 (collect at AnalysisRunner.scala:326) with 1 output partitions
2026-06-12 10:40:25,337 INFO scheduler.DAGScheduler: Final stage: ResultStage 4 (collect at AnalysisRunner.scala:326)
2026-06-12 10:40:25,337 INFO scheduler.DAGScheduler: Parents of final stage: List(ShuffleMapStage 3)
2026-06-12 10:40:25,337 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:25,338 INFO scheduler.DAGScheduler: Submitting ResultStage 4 (MapPartitionsRDD[19] at collect at AnalysisRunner.scala:326), which has no missing parents
2026-06-12 10:40:25,353 INFO memory.MemoryStore: Block broadcast_5 stored as values in memory (estimated size 166.5 KiB, free 1457.8 MiB)
2026-06-12 10:40:25,355 INFO memory.MemoryStore: Block broadcast_5_piece0 stored as bytes in memory (estimated size 45.9 KiB, free 1457.8 MiB)
2026-06-12 10:40:25,356 INFO storage.BlockManagerInfo: Added broadcast_5_piece0 in memory on 10.0.203.147:34811 (size: 45.9 KiB, free: 1458.5 MiB)
2026-06-12 10:40:25,357 INFO spark.SparkContext: Created broadcast 5 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:25,358 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 4 (MapPartitionsRDD[19] at collect at AnalysisRunner.scala:326) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:25,358 INFO cluster.YarnScheduler: Adding task set 4.0 with 1 tasks resource profile 0
2026-06-12 10:40:25,361 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 4.0 (TID 3) (algo-1, executor 1, partition 0, NODE_LOCAL, 4464 bytes) taskResourceAssignments Map()
2026-06-12 10:40:25,380 INFO storage.BlockManagerInfo: Added broadcast_5_piece0 in memory on algo-1:36143 (size: 45.9 KiB, free: 5.9 GiB)
2026-06-12 10:40:25,430 INFO spark.MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 0 to 10.0.203.147:48616
2026-06-12 10:40:25,743 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 4.0 (TID 3) in 383 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:25,744 INFO scheduler.DAGScheduler: ResultStage 4 (collect at AnalysisRunner.scala:326) finished in 0.398 s
2026-06-12 10:40:25,745 INFO scheduler.DAGScheduler: Job 3 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:25,745 INFO cluster.YarnScheduler: Removed TaskSet 4.0, whose tasks have all completed, from pool
2026-06-12 10:40:25,745 INFO cluster.YarnScheduler: Killing all running tasks in stage 4: Stage finished
2026-06-12 10:40:25,746 INFO scheduler.DAGScheduler: Job 3 finished: collect at AnalysisRunner.scala:326, took 0.411643 s
2026-06-12 10:40:25,799 INFO codegen.CodeGenerator: Code generated in 38.777256 ms
2026-06-12 10:40:26,155 INFO codegen.CodeGenerator: Code generated in 46.044946 ms
2026-06-12 10:40:26,262 INFO spark.SparkContext: Starting job: treeReduce at KLLRunner.scala:107
2026-06-12 10:40:26,264 INFO scheduler.DAGScheduler: Got job 4 (treeReduce at KLLRunner.scala:107) with 1 output partitions
2026-06-12 10:40:26,264 INFO scheduler.DAGScheduler: Final stage: ResultStage 5 (treeReduce at KLLRunner.scala:107)
2026-06-12 10:40:26,264 INFO scheduler.DAGScheduler: Parents of final stage: List()
2026-06-12 10:40:26,265 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:26,266 INFO scheduler.DAGScheduler: Submitting ResultStage 5 (MapPartitionsRDD[29] at treeReduce at KLLRunner.scala:107), which has no missing parents
2026-06-12 10:40:26,297 INFO memory.MemoryStore: Block broadcast_6 stored as values in memory (estimated size 37.7 KiB, free 1457.8 MiB)
2026-06-12 10:40:26,299 INFO memory.MemoryStore: Block broadcast_6_piece0 stored as bytes in memory (estimated size 16.2 KiB, free 1457.7 MiB)
2026-06-12 10:40:26,300 INFO storage.BlockManagerInfo: Added broadcast_6_piece0 in memory on 10.0.203.147:34811 (size: 16.2 KiB, free: 1458.5 MiB)
2026-06-12 10:40:26,301 INFO spark.SparkContext: Created broadcast 6 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:26,301 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 5 (MapPartitionsRDD[29] at treeReduce at KLLRunner.scala:107) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:26,301 INFO cluster.YarnScheduler: Adding task set 5.0 with 1 tasks resource profile 0
2026-06-12 10:40:26,303 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 5.0 (TID 4) (algo-1, executor 1, partition 0, PROCESS_LOCAL, 4968 bytes) taskResourceAssignments Map()
2026-06-12 10:40:26,329 INFO storage.BlockManagerInfo: Added broadcast_6_piece0 in memory on algo-1:36143 (size: 16.2 KiB, free: 5.9 GiB)
2026-06-12 10:40:26,662 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 5.0 (TID 4) in 359 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:26,662 INFO cluster.YarnScheduler: Removed TaskSet 5.0, whose tasks have all completed, from pool
2026-06-12 10:40:26,663 INFO scheduler.DAGScheduler: ResultStage 5 (treeReduce at KLLRunner.scala:107) finished in 0.393 s
2026-06-12 10:40:26,665 INFO scheduler.DAGScheduler: Job 4 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:26,666 INFO cluster.YarnScheduler: Killing all running tasks in stage 5: Stage finished
2026-06-12 10:40:26,667 INFO scheduler.DAGScheduler: Job 4 finished: treeReduce at KLLRunner.scala:107, took 0.404800 s
2026-06-12 10:40:27,419 INFO codegen.CodeGenerator: Code generated in 175.558071 ms
2026-06-12 10:40:27,428 INFO scheduler.DAGScheduler: Registering RDD 34 (collect at AnalysisRunner.scala:326) as input to shuffle 1
2026-06-12 10:40:27,428 INFO scheduler.DAGScheduler: Got map stage job 5 (collect at AnalysisRunner.scala:326) with 1 output partitions
2026-06-12 10:40:27,428 INFO scheduler.DAGScheduler: Final stage: ShuffleMapStage 6 (collect at AnalysisRunner.scala:326)
2026-06-12 10:40:27,428 INFO scheduler.DAGScheduler: Parents of final stage: List()
2026-06-12 10:40:27,429 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:27,430 INFO scheduler.DAGScheduler: Submitting ShuffleMapStage 6 (MapPartitionsRDD[34] at collect at AnalysisRunner.scala:326), which has no missing parents
2026-06-12 10:40:27,440 INFO memory.MemoryStore: Block broadcast_7 stored as values in memory (estimated size 73.6 KiB, free 1457.7 MiB)
2026-06-12 10:40:27,442 INFO memory.MemoryStore: Block broadcast_7_piece0 stored as bytes in memory (estimated size 23.6 KiB, free 1457.7 MiB)
2026-06-12 10:40:27,443 INFO storage.BlockManagerInfo: Added broadcast_7_piece0 in memory on 10.0.203.147:34811 (size: 23.6 KiB, free: 1458.4 MiB)
2026-06-12 10:40:27,444 INFO spark.SparkContext: Created broadcast 7 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:27,445 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 6 (MapPartitionsRDD[34] at collect at AnalysisRunner.scala:326) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:27,445 INFO cluster.YarnScheduler: Adding task set 6.0 with 1 tasks resource profile 0
2026-06-12 10:40:27,447 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 6.0 (TID 5) (algo-1, executor 1, partition 0, PROCESS_LOCAL, 4957 bytes) taskResourceAssignments Map()
2026-06-12 10:40:27,474 INFO storage.BlockManagerInfo: Added broadcast_7_piece0 in memory on algo-1:36143 (size: 23.6 KiB, free: 5.9 GiB)
2026-06-12 10:40:27,639 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 6.0 (TID 5) in 192 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:27,639 INFO cluster.YarnScheduler: Removed TaskSet 6.0, whose tasks have all completed, from pool
2026-06-12 10:40:27,640 INFO scheduler.DAGScheduler: ShuffleMapStage 6 (collect at AnalysisRunner.scala:326) finished in 0.206 s
2026-06-12 10:40:27,641 INFO scheduler.DAGScheduler: looking for newly runnable stages
2026-06-12 10:40:27,641 INFO scheduler.DAGScheduler: running: Set()
2026-06-12 10:40:27,641 INFO scheduler.DAGScheduler: waiting: Set()
2026-06-12 10:40:27,642 INFO scheduler.DAGScheduler: failed: Set()
2026-06-12 10:40:27,963 INFO codegen.CodeGenerator: Code generated in 119.156108 ms
2026-06-12 10:40:27,982 INFO spark.SparkContext: Starting job: collect at AnalysisRunner.scala:326
2026-06-12 10:40:27,984 INFO scheduler.DAGScheduler: Got job 6 (collect at AnalysisRunner.scala:326) with 1 output partitions
2026-06-12 10:40:27,985 INFO scheduler.DAGScheduler: Final stage: ResultStage 8 (collect at AnalysisRunner.scala:326)
2026-06-12 10:40:27,986 INFO scheduler.DAGScheduler: Parents of final stage: List(ShuffleMapStage 7)
2026-06-12 10:40:27,986 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:27,987 INFO scheduler.DAGScheduler: Submitting ResultStage 8 (MapPartitionsRDD[37] at collect at AnalysisRunner.scala:326), which has no missing parents
2026-06-12 10:40:28,000 INFO memory.MemoryStore: Block broadcast_8 stored as values in memory (estimated size 66.5 KiB, free 1457.6 MiB)
2026-06-12 10:40:28,003 INFO memory.MemoryStore: Block broadcast_8_piece0 stored as bytes in memory (estimated size 19.4 KiB, free 1457.6 MiB)
2026-06-12 10:40:28,004 INFO storage.BlockManagerInfo: Added broadcast_8_piece0 in memory on 10.0.203.147:34811 (size: 19.4 KiB, free: 1458.4 MiB)
2026-06-12 10:40:28,010 INFO spark.SparkContext: Created broadcast 8 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:28,010 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 8 (MapPartitionsRDD[37] at collect at AnalysisRunner.scala:326) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:28,010 INFO cluster.YarnScheduler: Adding task set 8.0 with 1 tasks resource profile 0
2026-06-12 10:40:28,012 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 8.0 (TID 6) (algo-1, executor 1, partition 0, NODE_LOCAL, 4464 bytes) taskResourceAssignments Map()
2026-06-12 10:40:28,027 INFO storage.BlockManagerInfo: Added broadcast_8_piece0 in memory on algo-1:36143 (size: 19.4 KiB, free: 5.9 GiB)
2026-06-12 10:40:28,039 INFO spark.MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 1 to 10.0.203.147:48616
2026-06-12 10:40:28,116 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 8.0 (TID 6) in 104 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:28,117 INFO cluster.YarnScheduler: Removed TaskSet 8.0, whose tasks have all completed, from pool
2026-06-12 10:40:28,124 INFO scheduler.DAGScheduler: ResultStage 8 (collect at AnalysisRunner.scala:326) finished in 0.130 s
2026-06-12 10:40:28,125 INFO scheduler.DAGScheduler: Job 6 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:28,125 INFO cluster.YarnScheduler: Killing all running tasks in stage 8: Stage finished
2026-06-12 10:40:28,126 INFO scheduler.DAGScheduler: Job 6 finished: collect at AnalysisRunner.scala:326, took 0.143438 s
2026-06-12 10:40:28,209 INFO codegen.CodeGenerator: Code generated in 65.022886 ms
2026-06-12 10:40:28,315 INFO spark.SparkContext: Starting job: countByKey at ColumnProfiler.scala:592
2026-06-12 10:40:28,321 INFO scheduler.DAGScheduler: Registering RDD 45 (countByKey at ColumnProfiler.scala:592) as input to shuffle 2
2026-06-12 10:40:28,322 INFO scheduler.DAGScheduler: Got job 7 (countByKey at ColumnProfiler.scala:592) with 1 output partitions
2026-06-12 10:40:28,322 INFO scheduler.DAGScheduler: Final stage: ResultStage 10 (countByKey at ColumnProfiler.scala:592)
2026-06-12 10:40:28,322 INFO scheduler.DAGScheduler: Parents of final stage: List(ShuffleMapStage 9)
2026-06-12 10:40:28,322 INFO scheduler.DAGScheduler: Missing parents: List(ShuffleMapStage 9)
2026-06-12 10:40:28,324 INFO scheduler.DAGScheduler: Submitting ShuffleMapStage 9 (MapPartitionsRDD[45] at countByKey at ColumnProfiler.scala:592), which has no missing parents
2026-06-12 10:40:28,335 INFO memory.MemoryStore: Block broadcast_9 stored as values in memory (estimated size 30.0 KiB, free 1457.5 MiB)
2026-06-12 10:40:28,337 INFO memory.MemoryStore: Block broadcast_9_piece0 stored as bytes in memory (estimated size 13.8 KiB, free 1457.5 MiB)
2026-06-12 10:40:28,338 INFO storage.BlockManagerInfo: Added broadcast_9_piece0 in memory on 10.0.203.147:34811 (size: 13.8 KiB, free: 1458.4 MiB)
2026-06-12 10:40:28,339 INFO spark.SparkContext: Created broadcast 9 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:28,340 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 9 (MapPartitionsRDD[45] at countByKey at ColumnProfiler.scala:592) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:28,340 INFO cluster.YarnScheduler: Adding task set 9.0 with 1 tasks resource profile 0
2026-06-12 10:40:28,342 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 9.0 (TID 7) (algo-1, executor 1, partition 0, PROCESS_LOCAL, 4957 bytes) taskResourceAssignments Map()
2026-06-12 10:40:28,364 INFO storage.BlockManagerInfo: Added broadcast_9_piece0 in memory on algo-1:36143 (size: 13.8 KiB, free: 5.9 GiB)
2026-06-12 10:40:29,905 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 9.0 (TID 7) in 1563 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:29,906 INFO cluster.YarnScheduler: Removed TaskSet 9.0, whose tasks have all completed, from pool
2026-06-12 10:40:29,909 INFO scheduler.DAGScheduler: ShuffleMapStage 9 (countByKey at ColumnProfiler.scala:592) finished in 1.583 s
2026-06-12 10:40:29,909 INFO scheduler.DAGScheduler: looking for newly runnable stages
2026-06-12 10:40:29,909 INFO scheduler.DAGScheduler: running: Set()
2026-06-12 10:40:29,909 INFO scheduler.DAGScheduler: waiting: Set(ResultStage 10)
2026-06-12 10:40:29,910 INFO scheduler.DAGScheduler: failed: Set()
2026-06-12 10:40:29,910 INFO scheduler.DAGScheduler: Submitting ResultStage 10 (ShuffledRDD[46] at countByKey at ColumnProfiler.scala:592), which has no missing parents
2026-06-12 10:40:29,913 INFO memory.MemoryStore: Block broadcast_10 stored as values in memory (estimated size 5.1 KiB, free 1457.5 MiB)
2026-06-12 10:40:29,915 INFO memory.MemoryStore: Block broadcast_10_piece0 stored as bytes in memory (estimated size 3.0 KiB, free 1457.5 MiB)
2026-06-12 10:40:29,918 INFO storage.BlockManagerInfo: Added broadcast_10_piece0 in memory on 10.0.203.147:34811 (size: 3.0 KiB, free: 1458.4 MiB)
2026-06-12 10:40:29,920 INFO spark.SparkContext: Created broadcast 10 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:29,922 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 10 (ShuffledRDD[46] at countByKey at ColumnProfiler.scala:592) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:29,922 INFO cluster.YarnScheduler: Adding task set 10.0 with 1 tasks resource profile 0
2026-06-12 10:40:29,926 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 10.0 (TID 8) (algo-1, executor 1, partition 0, NODE_LOCAL, 4282 bytes) taskResourceAssignments Map()
2026-06-12 10:40:29,949 INFO storage.BlockManagerInfo: Added broadcast_10_piece0 in memory on algo-1:36143 (size: 3.0 KiB, free: 5.9 GiB)
2026-06-12 10:40:29,964 INFO spark.MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 2 to 10.0.203.147:48616
2026-06-12 10:40:30,047 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 10.0 (TID 8) in 123 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:30,049 INFO cluster.YarnScheduler: Removed TaskSet 10.0, whose tasks have all completed, from pool
2026-06-12 10:40:30,050 INFO scheduler.DAGScheduler: ResultStage 10 (countByKey at ColumnProfiler.scala:592) finished in 0.139 s
2026-06-12 10:40:30,058 INFO scheduler.DAGScheduler: Job 7 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:30,059 INFO cluster.YarnScheduler: Killing all running tasks in stage 10: Stage finished
2026-06-12 10:40:30,059 INFO scheduler.DAGScheduler: Job 7 finished: countByKey at ColumnProfiler.scala:592, took 1.744324 s
2026-06-12 10:40:30,372 INFO scheduler.DAGScheduler: Registering RDD 51 (collect at AnalysisRunner.scala:326) as input to shuffle 3
2026-06-12 10:40:30,372 INFO scheduler.DAGScheduler: Got map stage job 8 (collect at AnalysisRunner.scala:326) with 1 output partitions
2026-06-12 10:40:30,373 INFO scheduler.DAGScheduler: Final stage: ShuffleMapStage 11 (collect at AnalysisRunner.scala:326)
2026-06-12 10:40:30,373 INFO scheduler.DAGScheduler: Parents of final stage: List()
2026-06-12 10:40:30,374 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:30,375 INFO scheduler.DAGScheduler: Submitting ShuffleMapStage 11 (MapPartitionsRDD[51] at collect at AnalysisRunner.scala:326), which has no missing parents
2026-06-12 10:40:30,385 INFO memory.MemoryStore: Block broadcast_11 stored as values in memory (estimated size 82.9 KiB, free 1457.4 MiB)

2026-06-12 10:40:33,094 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 23.0 (TID 18) in 93 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:33,095 INFO cluster.YarnScheduler: Removed TaskSet 23.0, whose tasks have all completed, from pool
2026-06-12 10:40:33,096 INFO scheduler.DAGScheduler: ResultStage 23 (treeReduce at KLLRunner.scala:107) finished in 0.109 s
2026-06-12 10:40:33,097 INFO scheduler.DAGScheduler: Job 16 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:33,097 INFO cluster.YarnScheduler: Killing all running tasks in stage 23: Stage finished
2026-06-12 10:40:33,097 INFO scheduler.DAGScheduler: Job 16 finished: treeReduce at KLLRunner.scala:107, took 0.114808 s
2026-06-12 10:40:33,283 INFO codegen.CodeGenerator: Code generated in 38.622861 ms
2026-06-12 10:40:33,290 INFO scheduler.DAGScheduler: Registering RDD 104 (collect at AnalysisRunner.scala:326) as input to shuffle 7
2026-06-12 10:40:33,291 INFO scheduler.DAGScheduler: Got map stage job 17 (collect at AnalysisRunner.scala:326) with 1 output partitions
2026-06-12 10:40:33,291 INFO scheduler.DAGScheduler: Final stage: ShuffleMapStage 24 (collect at AnalysisRunner.scala:326)
2026-06-12 10:40:33,291 INFO scheduler.DAGScheduler: Parents of final stage: List()
2026-06-12 10:40:33,292 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:33,293 INFO scheduler.DAGScheduler: Submitting ShuffleMapStage 24 (MapPartitionsRDD[104] at collect at AnalysisRunner.scala:326), which has no missing parents
2026-06-12 10:40:33,296 INFO memory.MemoryStore: Block broadcast_21 stored as values in memory (estimated size 32.5 KiB, free 1457.8 MiB)
2026-06-12 10:40:33,298 INFO memory.MemoryStore: Block broadcast_21_piece0 stored as bytes in memory (estimated size 13.2 KiB, free 1457.8 MiB)
2026-06-12 10:40:33,299 INFO storage.BlockManagerInfo: Added broadcast_21_piece0 in memory on 10.0.203.147:34811 (size: 13.2 KiB, free: 1458.5 MiB)
2026-06-12 10:40:33,300 INFO spark.SparkContext: Created broadcast 21 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:33,309 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 24 (MapPartitionsRDD[104] at collect at AnalysisRunner.scala:326) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:33,309 INFO cluster.YarnScheduler: Adding task set 24.0 with 1 tasks resource profile 0
2026-06-12 10:40:33,311 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 24.0 (TID 19) (algo-1, executor 1, partition 0, PROCESS_LOCAL, 4957 bytes) taskResourceAssignments Map()
2026-06-12 10:40:33,331 INFO storage.BlockManagerInfo: Added broadcast_21_piece0 in memory on algo-1:36143 (size: 13.2 KiB, free: 5.9 GiB)
2026-06-12 10:40:33,367 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 24.0 (TID 19) in 56 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:33,367 INFO cluster.YarnScheduler: Removed TaskSet 24.0, whose tasks have all completed, from pool
2026-06-12 10:40:33,368 INFO scheduler.DAGScheduler: ShuffleMapStage 24 (collect at AnalysisRunner.scala:326) finished in 0.074 s
2026-06-12 10:40:33,368 INFO scheduler.DAGScheduler: looking for newly runnable stages
2026-06-12 10:40:33,368 INFO scheduler.DAGScheduler: running: Set()
2026-06-12 10:40:33,368 INFO scheduler.DAGScheduler: waiting: Set()
2026-06-12 10:40:33,368 INFO scheduler.DAGScheduler: failed: Set()
2026-06-12 10:40:33,426 INFO codegen.CodeGenerator: Code generated in 37.339874 ms
2026-06-12 10:40:33,451 INFO spark.SparkContext: Starting job: collect at AnalysisRunner.scala:326
2026-06-12 10:40:33,452 INFO scheduler.DAGScheduler: Got job 18 (collect at AnalysisRunner.scala:326) with 1 output partitions
2026-06-12 10:40:33,452 INFO scheduler.DAGScheduler: Final stage: ResultStage 26 (collect at AnalysisRunner.scala:326)
2026-06-12 10:40:33,452 INFO scheduler.DAGScheduler: Parents of final stage: List(ShuffleMapStage 25)
2026-06-12 10:40:33,452 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:33,454 INFO scheduler.DAGScheduler: Submitting ResultStage 26 (MapPartitionsRDD[107] at collect at AnalysisRunner.scala:326), which has no missing parents
2026-06-12 10:40:33,456 INFO memory.MemoryStore: Block broadcast_22 stored as values in memory (estimated size 21.4 KiB, free 1457.8 MiB)
2026-06-12 10:40:33,459 INFO memory.MemoryStore: Block broadcast_22_piece0 stored as bytes in memory (estimated size 8.5 KiB, free 1457.8 MiB)
2026-06-12 10:40:33,460 INFO storage.BlockManagerInfo: Added broadcast_22_piece0 in memory on 10.0.203.147:34811 (size: 8.5 KiB, free: 1458.5 MiB)
2026-06-12 10:40:33,461 INFO spark.SparkContext: Created broadcast 22 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:33,462 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 26 (MapPartitionsRDD[107] at collect at AnalysisRunner.scala:326) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:33,462 INFO cluster.YarnScheduler: Adding task set 26.0 with 1 tasks resource profile 0
2026-06-12 10:40:33,463 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 26.0 (TID 20) (algo-1, executor 1, partition 0, NODE_LOCAL, 4464 bytes) taskResourceAssignments Map()
2026-06-12 10:40:33,483 INFO storage.BlockManagerInfo: Added broadcast_22_piece0 in memory on algo-1:36143 (size: 8.5 KiB, free: 5.9 GiB)
2026-06-12 10:40:33,492 INFO spark.MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 7 to 10.0.203.147:48616
2026-06-12 10:40:33,540 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 26.0 (TID 20) in 77 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:33,541 INFO cluster.YarnScheduler: Removed TaskSet 26.0, whose tasks have all completed, from pool
2026-06-12 10:40:33,541 INFO scheduler.DAGScheduler: ResultStage 26 (collect at AnalysisRunner.scala:326) finished in 0.086 s
2026-06-12 10:40:33,542 INFO scheduler.DAGScheduler: Job 18 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:33,542 INFO cluster.YarnScheduler: Killing all running tasks in stage 26: Stage finished
2026-06-12 10:40:33,542 INFO scheduler.DAGScheduler: Job 18 finished: collect at AnalysisRunner.scala:326, took 0.090543 s
2026-06-12 10:40:33,605 INFO codegen.CodeGenerator: Code generated in 54.965326 ms
2026-06-12 10:40:33,668 INFO spark.SparkContext: Starting job: countByKey at ColumnProfiler.scala:592
2026-06-12 10:40:33,670 INFO scheduler.DAGScheduler: Registering RDD 115 (countByKey at ColumnProfiler.scala:592) as input to shuffle 8
2026-06-12 10:40:33,671 INFO scheduler.DAGScheduler: Got job 19 (countByKey at ColumnProfiler.scala:592) with 1 output partitions
2026-06-12 10:40:33,671 INFO scheduler.DAGScheduler: Final stage: ResultStage 28 (countByKey at ColumnProfiler.scala:592)
2026-06-12 10:40:33,671 INFO scheduler.DAGScheduler: Parents of final stage: List(ShuffleMapStage 27)
2026-06-12 10:40:33,671 INFO scheduler.DAGScheduler: Missing parents: List(ShuffleMapStage 27)
2026-06-12 10:40:33,675 INFO scheduler.DAGScheduler: Submitting ShuffleMapStage 27 (MapPartitionsRDD[115] at countByKey at ColumnProfiler.scala:592), which has no missing parents
2026-06-12 10:40:33,681 INFO memory.MemoryStore: Block broadcast_23 stored as values in memory (estimated size 29.5 KiB, free 1457.7 MiB)
2026-06-12 10:40:33,685 INFO memory.MemoryStore: Block broadcast_23_piece0 stored as bytes in memory (estimated size 13.7 KiB, free 1457.7 MiB)
2026-06-12 10:40:33,688 INFO storage.BlockManagerInfo: Added broadcast_23_piece0 in memory on 10.0.203.147:34811 (size: 13.7 KiB, free: 1458.4 MiB)
2026-06-12 10:40:33,689 INFO spark.SparkContext: Created broadcast 23 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:33,690 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 27 (MapPartitionsRDD[115] at countByKey at ColumnProfiler.scala:592) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:33,690 INFO cluster.YarnScheduler: Adding task set 27.0 with 1 tasks resource profile 0
2026-06-12 10:40:33,693 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 27.0 (TID 21) (algo-1, executor 1, partition 0, PROCESS_LOCAL, 4957 bytes) taskResourceAssignments Map()
2026-06-12 10:40:33,736 INFO storage.BlockManagerInfo: Added broadcast_23_piece0 in memory on algo-1:36143 (size: 13.7 KiB, free: 5.9 GiB)
2026-06-12 10:40:33,813 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 27.0 (TID 21) in 119 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:33,813 INFO cluster.YarnScheduler: Removed TaskSet 27.0, whose tasks have all completed, from pool
2026-06-12 10:40:33,814 INFO scheduler.DAGScheduler: ShuffleMapStage 27 (countByKey at ColumnProfiler.scala:592) finished in 0.138 s
2026-06-12 10:40:33,814 INFO scheduler.DAGScheduler: looking for newly runnable stages
2026-06-12 10:40:33,814 INFO scheduler.DAGScheduler: running: Set()
2026-06-12 10:40:33,814 INFO scheduler.DAGScheduler: waiting: Set(ResultStage 28)
2026-06-12 10:40:33,814 INFO scheduler.DAGScheduler: failed: Set()
2026-06-12 10:40:33,814 INFO scheduler.DAGScheduler: Submitting ResultStage 28 (ShuffledRDD[116] at countByKey at ColumnProfiler.scala:592), which has no missing parents
2026-06-12 10:40:33,818 INFO memory.MemoryStore: Block broadcast_24 stored as values in memory (estimated size 5.1 KiB, free 1457.7 MiB)
2026-06-12 10:40:33,820 INFO memory.MemoryStore: Block broadcast_24_piece0 stored as bytes in memory (estimated size 3.0 KiB, free 1457.7 MiB)
2026-06-12 10:40:33,821 INFO storage.BlockManagerInfo: Added broadcast_24_piece0 in memory on 10.0.203.147:34811 (size: 3.0 KiB, free: 1458.4 MiB)
2026-06-12 10:40:33,822 INFO spark.SparkContext: Created broadcast 24 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:33,822 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 28 (ShuffledRDD[116] at countByKey at ColumnProfiler.scala:592) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:33,823 INFO cluster.YarnScheduler: Adding task set 28.0 with 1 tasks resource profile 0
2026-06-12 10:40:33,825 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 28.0 (TID 22) (algo-1, executor 1, partition 0, NODE_LOCAL, 4282 bytes) taskResourceAssignments Map()
2026-06-12 10:40:33,842 INFO storage.BlockManagerInfo: Added broadcast_24_piece0 in memory on algo-1:36143 (size: 3.0 KiB, free: 5.9 GiB)
2026-06-12 10:40:33,849 INFO spark.MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 8 to 10.0.203.147:48616
2026-06-12 10:40:33,871 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 28.0 (TID 22) in 46 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:33,871 INFO cluster.YarnScheduler: Removed TaskSet 28.0, whose tasks have all completed, from pool
2026-06-12 10:40:33,872 INFO scheduler.DAGScheduler: ResultStage 28 (countByKey at ColumnProfiler.scala:592) finished in 0.057 s
2026-06-12 10:40:33,873 INFO scheduler.DAGScheduler: Job 19 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:33,874 INFO cluster.YarnScheduler: Killing all running tasks in stage 28: Stage finished
2026-06-12 10:40:33,874 INFO scheduler.DAGScheduler: Job 19 finished: countByKey at ColumnProfiler.scala:592, took 0.205116 s
2026-06-12 10:40:34,161 INFO FileUtil: Write to file constraints.json at path /opt/ml/processing/output.
2026-06-12 10:40:34,198 INFO codegen.CodeGenerator: Code generated in 11.184234 ms
2026-06-12 10:40:34,205 INFO scheduler.DAGScheduler: Registering RDD 121 (count at StatsGenerator.scala:66) as input to shuffle 9
2026-06-12 10:40:34,205 INFO scheduler.DAGScheduler: Got map stage job 20 (count at StatsGenerator.scala:66) with 1 output partitions
2026-06-12 10:40:34,206 INFO scheduler.DAGScheduler: Final stage: ShuffleMapStage 29 (count at StatsGenerator.scala:66)
2026-06-12 10:40:34,206 INFO scheduler.DAGScheduler: Parents of final stage: List()
2026-06-12 10:40:34,206 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:34,206 INFO scheduler.DAGScheduler: Submitting ShuffleMapStage 29 (MapPartitionsRDD[121] at count at StatsGenerator.scala:66), which has no missing parents
2026-06-12 10:40:34,210 INFO memory.MemoryStore: Block broadcast_25 stored as values in memory (estimated size 22.0 KiB, free 1457.7 MiB)
2026-06-12 10:40:34,212 INFO memory.MemoryStore: Block broadcast_25_piece0 stored as bytes in memory (estimated size 10.2 KiB, free 1457.7 MiB)
2026-06-12 10:40:34,213 INFO storage.BlockManagerInfo: Added broadcast_25_piece0 in memory on 10.0.203.147:34811 (size: 10.2 KiB, free: 1458.4 MiB)
2026-06-12 10:40:34,214 INFO spark.SparkContext: Created broadcast 25 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:34,214 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 29 (MapPartitionsRDD[121] at count at StatsGenerator.scala:66) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:34,215 INFO cluster.YarnScheduler: Adding task set 29.0 with 1 tasks resource profile 0
2026-06-12 10:40:34,216 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 29.0 (TID 23) (algo-1, executor 1, partition 0, PROCESS_LOCAL, 4957 bytes) taskResourceAssignments Map()
2026-06-12 10:40:34,229 INFO storage.BlockManagerInfo: Added broadcast_25_piece0 in memory on algo-1:36143 (size: 10.2 KiB, free: 5.9 GiB)
2026-06-12 10:40:34,290 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 29.0 (TID 23) in 74 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:34,290 INFO cluster.YarnScheduler: Removed TaskSet 29.0, whose tasks have all completed, from pool
2026-06-12 10:40:34,291 INFO scheduler.DAGScheduler: ShuffleMapStage 29 (count at StatsGenerator.scala:66) finished in 0.084 s
2026-06-12 10:40:34,291 INFO scheduler.DAGScheduler: looking for newly runnable stages
2026-06-12 10:40:34,292 INFO scheduler.DAGScheduler: running: Set()
2026-06-12 10:40:34,292 INFO scheduler.DAGScheduler: waiting: Set()
2026-06-12 10:40:34,292 INFO scheduler.DAGScheduler: failed: Set()
2026-06-12 10:40:34,311 INFO codegen.CodeGenerator: Code generated in 10.814367 ms
2026-06-12 10:40:34,334 INFO spark.SparkContext: Starting job: count at StatsGenerator.scala:66
2026-06-12 10:40:34,336 INFO scheduler.DAGScheduler: Got job 21 (count at StatsGenerator.scala:66) with 1 output partitions
2026-06-12 10:40:34,336 INFO scheduler.DAGScheduler: Final stage: ResultStage 31 (count at StatsGenerator.scala:66)
2026-06-12 10:40:34,337 INFO scheduler.DAGScheduler: Parents of final stage: List(ShuffleMapStage 30)
2026-06-12 10:40:34,337 INFO scheduler.DAGScheduler: Missing parents: List()
2026-06-12 10:40:34,337 INFO scheduler.DAGScheduler: Submitting ResultStage 31 (MapPartitionsRDD[124] at count at StatsGenerator.scala:66), which has no missing parents
2026-06-12 10:40:34,339 INFO memory.MemoryStore: Block broadcast_26 stored as values in memory (estimated size 11.1 KiB, free 1457.7 MiB)
2026-06-12 10:40:34,342 INFO memory.MemoryStore: Block broadcast_26_piece0 stored as bytes in memory (estimated size 5.5 KiB, free 1457.7 MiB)
2026-06-12 10:40:34,344 INFO storage.BlockManagerInfo: Added broadcast_26_piece0 in memory on 10.0.203.147:34811 (size: 5.5 KiB, free: 1458.4 MiB)
2026-06-12 10:40:34,345 INFO spark.SparkContext: Created broadcast 26 from broadcast at DAGScheduler.scala:1513
2026-06-12 10:40:34,345 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 31 (MapPartitionsRDD[124] at count at StatsGenerator.scala:66) (first 15 tasks are for partitions Vector(0))
2026-06-12 10:40:34,346 INFO cluster.YarnScheduler: Adding task set 31.0 with 1 tasks resource profile 0
2026-06-12 10:40:34,348 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 31.0 (TID 24) (algo-1, executor 1, partition 0, NODE_LOCAL, 4464 bytes) taskResourceAssignments Map()
2026-06-12 10:40:34,362 INFO storage.BlockManagerInfo: Added broadcast_26_piece0 in memory on algo-1:36143 (size: 5.5 KiB, free: 5.9 GiB)
2026-06-12 10:40:34,367 INFO spark.MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 9 to 10.0.203.147:48616
2026-06-12 10:40:34,405 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 31.0 (TID 24) in 57 ms on algo-1 (executor 1) (1/1)
2026-06-12 10:40:34,406 INFO cluster.YarnScheduler: Removed TaskSet 31.0, whose tasks have all completed, from pool
2026-06-12 10:40:34,413 INFO scheduler.DAGScheduler: ResultStage 31 (count at StatsGenerator.scala:66) finished in 0.074 s
2026-06-12 10:40:34,413 INFO scheduler.DAGScheduler: Job 21 is finished. Cancelling potential speculative or zombie tasks for this job
2026-06-12 10:40:34,414 INFO cluster.YarnScheduler: Killing all running tasks in stage 31: Stage finished
2026-06-12 10:40:34,415 INFO scheduler.DAGScheduler: Job 21 finished: count at StatsGenerator.scala:66, took 0.079402 s
2026-06-12 10:40:34,733 INFO FileUtil: Write to file statistics.json at path /opt/ml/processing/output.
2026-06-12 10:40:34,748 INFO cluster.YarnClientSchedulerBackend: Interrupting monitor thread
2026-06-12 10:40:34,782 INFO cluster.YarnClientSchedulerBackend: Shutting down all executors
2026-06-12 10:40:34,783 INFO cluster.YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
2026-06-12 10:40:34,796 INFO cluster.YarnClientSchedulerBackend: YARN client scheduler backend Stopped
2026-06-12 10:40:34,830 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
2026-06-12 10:40:34,883 INFO memory.MemoryStore: MemoryStore cleared
2026-06-12 10:40:34,883 INFO storage.BlockManager: BlockManager stopped
2026-06-12 10:40:34,900 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
2026-06-12 10:40:34,904 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
2026-06-12 10:40:34,950 INFO spark.SparkContext: Successfully stopped SparkContext
2026-06-12 10:40:34,951 INFO Main: Completed: Job completed successfully with no violations.
2026-06-12 10:40:34,951 INFO Main: Write to file /opt/ml/output/message.
2026-06-12 10:40:34,966 INFO util.ShutdownHookManager: Shutdown hook called
2026-06-12 10:40:34,967 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-5e6ee794-d376-4f0a-bfbe-98f3a15f889f
2026-06-12 10:40:34,971 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-1eb31a4f-214b-441a-8f6d-c10b7ad828a5
2026-06-12 10:40:35,055 - DefaultDataAnalyzer - INFO - Completed spark-submit with return code : 0
2026-06-12 10:40:35,056 - DefaultDataAnalyzer - INFO - Spark job completed.

<i class="fas fa-sticky-note" style="color:#ec7211"></i> **NOTE:** This code returns a lengthy response. You can ignore any warnings or error messages.

<i class="fas fa-sticky-note" style="color:#ec7211"></i> **NOTE:** When the cell completes, a message is returned that looks like *2025-10-11 12:13:14,156 - DefaultDataAnalyzer - INFO - Spark job completed*.

Now, search for the *constraints.json* and *statistics.json* files to see where they are located.

In [10]:
#explore-generated-constraints-and-statistics
s3_client = boto3.Session().client("s3")
result = s3_client.list_objects(Bucket=bucket, Prefix=baseline_results_prefix)
report_files = [report_file.get("Key") for report_file in result.get("Contents")]
print("Found Files:")
print("\n ".join(report_files))

Found Files:
sagemaker/abalone/baselining/results/constraints.json
 sagemaker/abalone/baselining/results/statistics.json

Next, view the generated statistics.

In [11]:
#view-statistics
baseline_job = my_default_monitor.latest_baselining_job
schema_df = pd.json_normalize(baseline_job.baseline_statistics().body_dict["features"])
schema_df.head(10)

,name,inferred_type,numerical_statistics.common.num_present,numerical_statistics.common.num_missing,numerical_statistics.mean,numerical_statistics.sum,numerical_statistics.std_dev,numerical_statistics.min,numerical_statistics.max,numerical_statistics.approximate_num_distinct_values,numerical_statistics.completeness,numerical_statistics.distribution.kll.buckets,numerical_statistics.distribution.kll.sketch.parameters.c,numerical_statistics.distribution.kll.sketch.parameters.k,numerical_statistics.distribution.kll.sketch.data
0,rings,Integral,120,0,9.991667e+00,1.199000e+03,2.378711,4.000000,17.000000,13,1.0,"[{'lower_bound': 4.0, 'upper_bound': 5.3, 'cou...",0.64,2048.0,"[[11.0, 12.0, 10.0, 10.0, 13.0, 11.0, 11.0, 10..."
1,length,Fractional,120,0,-2.500000e-11,-3.000000e-09,1.000000,-3.132857,1.792725,60,1.0,"[{'lower_bound': -3.13285749, 'upper_bound': -...",0.64,2048.0,"[[0.842173735, 1.40386293, 1.187828624, 0.9285..."
2,diameter,Fractional,120,0,1.666667e-11,2.000000e-09,1.000000,-3.116738,1.574943,54,1.0,"[{'lower_bound': -3.116738385, 'upper_bound': ...",0.64,2048.0,"[[0.860991542, 1.523946529, 0.962984617, 0.962..."
3,height,Fractional,120,0,-8.326673e-17,-9.992007e-15,1.000000,-2.590157,1.918424,29,1.0,"[{'lower_bound': -2.590157076, 'upper_bound': ...",0.64,2048.0,"[[0.688811003, 1.645176692, 1.098682012, 1.235..."
4,whole_weight,Fractional,120,0,1.666665e-11,1.999998e-09,1.000000,-1.777180,3.316178,119,1.0,"[{'lower_bound': -1.777179983, 'upper_bound': ...",0.64,2048.0,"[[0.797789649, 2.556957875, 1.439731739, 1.895..."
5,shucked_weight,Fractional,120,0,1.666675e-11,2.000010e-09,1.000000,-1.864274,3.056230,119,1.0,"[{'lower_bound': -1.864273528, 'upper_bound': ...",0.64,2048.0,"[[0.819637499, 2.065165072, 1.808023895, 1.861..."
6,viscera_weight,Fractional,120,0,-1.666667e-11,-2.000000e-09,1.000000,-1.751453,2.736338,101,1.0,"[{'lower_bound': -1.751452951, 'upper_bound': ...",0.64,2048.0,"[[0.854509788, 2.736337747, 1.315742131, 1.800..."
7,shell_weight,Fractional,120,0,1.666669e-11,2.000003e-09,1.000000,-1.849493,2.974287,75,1.0,"[{'lower_bound': -1.849493312, 'upper_bound': ...",0.64,2048.0,"[[0.46480584, 2.137793179, 0.848198772, 0.8481..."
8,sex_m,Integral,120,0,4.083333e-01,4.900000e+01,0.491525,0.000000,1.000000,2,1.0,"[{'lower_bound': 0.0, 'upper_bound': 0.1, 'cou...",0.64,2048.0,"[[0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0,..."
9,sex_f,Integral,120,0,1.833333e-01,2.200000e+01,0.386940,0.000000,1.000000,2,1.0,"[{'lower_bound': 0.0, 'upper_bound': 0.1, 'cou...",0.64,2048.0,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."

The statistics table shows each feature with its corresponding summary statistics, including the mean, standard deviation, min, max, and other important details.

Finally, view the generated constraints.

In [12]:
#view-constraints
constraints_df = pd.json_normalize(
    baseline_job.suggested_constraints().body_dict["features"]
)
constraints_df.head(10)

             name inferred_type  completeness  num_constraints.is_non_negative
0           rings      Integral           1.0                             True
1          length    Fractional           1.0                            False
2        diameter    Fractional           1.0                            False
3          height    Fractional           1.0                            False
4    whole_weight    Fractional           1.0                            False
5  shucked_weight    Fractional           1.0                            False
6  viscera_weight    Fractional           1.0                            False
7    shell_weight    Fractional           1.0                            False
8           sex_m      Integral           1.0                             True
9           sex_f      Integral           1.0                             True

The constraints table shows the inferred type of each feature, the record completeness (in this case 1.0 for all features because the file has no missing values), and the fields that have no non-negative values. 

Now that you have a baseline created and have viewed the statistics and constraints, create a Model Monitor data quality monitoring job to track new inference records against the baseline.

# Task 2.5: Create a Model Monitor data quality monitoring job

After you create your baseline, you can call the *create_monitoring_schedule()* method of the *DefaultModelMonitor* class instance to schedule an hourly data quality monitor.

In this task, you analyze and monitor the data with a data quality monitoring job.

First, use the *create_monitoring_schedule()* method to schedule an hourly data quality monitoring schedule.

In [13]:
#create-monitoring-schedule
s3_bucket = boto3.Session().resource("s3").Bucket(bucket)
s3_bucket.Object(code_prefix + "/postprocessor.py").upload_file(f"{repo_path}/python/postprocessor.py")

mon_schedule_name = f"model-monitor-schedule-{datetime.now():%Y-%m-%d-%H-%M-%S}"

my_default_monitor.create_monitoring_schedule(
    monitor_schedule_name=mon_schedule_name,
    endpoint_input=predictor.endpoint_name,
    post_analytics_processor_script=s3_code_postprocessor_uri,
    output_s3_uri=s3_report_path,
    statistics=my_default_monitor.baseline_statistics(),
    constraints=my_default_monitor.suggested_constraints(),
    schedule_cron_expression=CronExpressionGenerator.hourly(),
    enable_cloudwatch_metrics=True,
)

INFO:sagemaker.model_monitor.model_monitoring:Creating Monitoring Schedule with name: model-monitor-schedule-2026-06-12-10-54-56

Next, send some artificial traffic to the endpoint for the monitoring job to be able to generate the violations report. To simulate data drift, use a set of skewed data. The skewed data, when compared against the baseline, throws an alert with the automated alert triggering system.

In [14]:
#send-artificial-traffic
endpoint_name = predictor.endpoint_name
runtime_client = sm_session.sagemaker_runtime_client
limit = 200
i = 0

# repeating code from above to run this section independently
def invoke_endpoint(ep_name, file_name, runtime_client):
    i = 0
    with open(file_name, "r") as f:
        for row in f:
            (label, payload) = row.strip("\n").split(",", 1)  

            response = runtime_client.invoke_endpoint(
                EndpointName=ep_name, ContentType="text/csv", Body=payload
            )
            response["Body"].read()
            i += 1
            if i > limit:
                break
            print(".", end="", flush=True)
            time.sleep(0.5)


invoke_endpoint(endpoint_name, f"{repo_path}/data/abalone_data_skewed.csv", runtime_client)
print("\nDone!")

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

.

Done!

Use *describe_schedule* to view the schedule you just created.

In [15]:
#model-monitor-schedule-status
desc_schedule_result = my_default_monitor.describe_schedule()
print("Schedule status: {}".format(desc_schedule_result["MonitoringScheduleStatus"]))

Schedule status: Scheduled

The monitor schedule starts jobs at the previously specified hourly interval. Even for an hourly schedule, SageMaker AI has a buffer period of 20 minutes to schedule your execution. You might see your execution start anywhere from 0 to 20 minutes from the hour boundary. This is expected and done for load balancing in the backend.

This execution takes approximately one hour to be able to generate the violations report. For the purpose of the lab, the next cells have code snippets for you to view and sample output is shared for reference. In the last step of this task, you view the violations report from a file that was generated and pre-loaded from an earlier monitoring run.

When the execution finishes, SageMaker AI reports the status of the latest completed or failed execution. 

Here are the possible terminal states:
- **Completed** - The monitoring execution completed and no issues were found in the violations report. 
- **CompletedWithViolations** - The execution completed, but constraint violations were detected. 
- **Failed** - The monitoring execution failed, maybe due to client error (perhaps incorrect role permissions) or infrastructure issues. Further examination of FailureReason and ExitMessage is necessary to identify what exactly happened. 
- **Stopped** - The job exceeded max runtime or was manually stopped.

If you want to list and view the current status of an execution, you can use code similar to this:

```python 
# list the current execution
mon_executions = my_default_monitor.list_executions()
print(
    "We created a hourly schedule above that begins executions ON the hour (plus 0-20 min buffer.\nWe will have to wait for an hour..."
)

while len(mon_executions) == 0:
    print("Waiting for the first execution to happen...")
    time.sleep(60)
    mon_executions = my_default_monitor.list_executions()
```



```python
# Latest execution status
latest_execution = mon_executions[-1]  # Latest execution's index is -1, second to last is -2, etc
time.sleep(60)
latest_execution.wait(logs=False)

print("Latest execution status: {}".format(latest_execution.describe()["ProcessingJobStatus"]))
print("Latest execution result: {}".format(latest_execution.describe()["ExitMessage"]))

latest_job = latest_execution.describe()
if latest_job["ProcessingJobStatus"] != "Completed":
    print(
        "====STOP==== \n No completed executions to inspect further. Please wait till an execution completes or investigate previously reported failures."
    )
```

The following is the expected output when the latest execution of the monitoring job completes.

```bash
!Latest execution status: Completed

Latest execution result: CompletedWithViolations: Job completed successfully with 8 violations.
```

To list the generated violation report, you can use code similar to this:

```python

from urllib.parse import urlparse

report_uri = latest_execution.output.destination
s3uri = urlparse(report_uri)
report_bucket = s3uri.netloc
report_key = s3uri.path.lstrip("/")
s3_client = boto3.Session().client("s3")
result = s3_client.list_objects(Bucket=report_bucket, Prefix=report_key)
report_files = [report_file.get("Key") for report_file in result.get("Contents")]
print("Found Report Files:")
print("\n ".join(report_files))
```

The following is the listing the report files.

```bash
Found Report Files:
sagemaker/abalone/reports/Abalone-2023-09-20-17-05-28/model-monitor-schedule-2023-09-20-17-41-22/2023/09/20/18/constraint_violations.json

sagemaker/abalone/reports/Abalone-2023-09-20-17-05-28/model-monitor-schedule-2023-09-20-17-41-22/2023/09/20/18/constraints.json

sagemaker/abalone/reports/Abalone-2023-09-20-17-05-28/model-monitor-schedule-2023-09-20-17-41-22/2023/09/20/18/statistics.json
```

To list violations compare to the baseline, you can use code similar to this:

```python
violations = my_default_monitor.latest_monitoring_constraint_violations()
pd.set_option("display.max_colwidth", None)
constraints_df = pd.json_normalize(violations.body_dict["violations"])
constraints_df.head(10)
```

Since the execution of the monitoring job you started above will not finish for 60-80 minutes, view a violations report from a file that was generated and pre-loaded from an earlier monitoring run.

In [16]:
#print-violations-report
pd.set_option('display.max_colwidth', None)
violations = json.load(open(f'{repo_path}/data/violations.json'))
constraints_df=pd.json_normalize(violations, record_path=['violations'])
constraints_df.head(10)

,feature_name,constraint_check_type,description
0,rings,data_type_check,"Data type match requirement is not met. Expected data type: Integral, Expected match: 100.0%. Observed: Only 0.0% of data is Integral."
1,sex_f,data_type_check,"Data type match requirement is not met. Expected data type: Integral, Expected match: 100.0%. Observed: Only 62.616822429906534% of data is Integral."
2,sex_i,data_type_check,"Data type match requirement is not met. Expected data type: Integral, Expected match: 100.0%. Observed: Only 62.616822429906534% of data is Integral."
3,sex_m,data_type_check,"Data type match requirement is not met. Expected data type: Integral, Expected match: 100.0%. Observed: Only 62.616822429906534% of data is Integral."
4,length,baseline_drift_check,Baseline drift distance: 0.17354640931273702 exceeds threshold: 0.1
5,diameter,baseline_drift_check,Baseline drift distance: 0.14440240796849557 exceeds threshold: 0.1
6,whole_weight,baseline_drift_check,Baseline drift distance: 0.11630482464065406 exceeds threshold: 0.1
7,shell_weight,baseline_drift_check,Baseline drift distance: 0.11238588915222741 exceeds threshold: 0.1

The violations report shows eight violations from the skewed data file, with four **data_type_check** violations for **rings**, **sex_f**, **sex_i**, and **sex_m**, and four **baseline_drift_check** violations for **length**, **diameter**, **whole_weight**, and **shell_weight**.

Take a moment to view the description for each violation. Notice that the data type matches were not correct for some of the features. Also, notice that the baseline drift distance exceeded the *0.1* threshold for the four reported features.

<i class="fas fa-sticky-note" style="color:#ff6633" aria-hidden="true"></i> **Note:** When you created a baseline job, it produced constraints.json and statistics.json files. In the *constraints.json* file, the *comparison_threshold* is set to *0.1* by default. To learn more about constraints.json file, refer [Schema for Constraints](https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-byoc-constraints.html).

## Task 2.6: Create a CloudWatch alarm

When data drift happens, it is helpful to get notifications so you can address any issues. A notification or alarm can also trigger automatic model retraining to address changes that might be occurring with your inference data.

In this task, you learn how to create alarm and enable notifications to know when data drifts away from baseline data.

First, find your current Amazon Simple Notification Service(Amazon SNS) topics by using **list_topics**.

In [17]:
#list-topics
client = boto3.client('sns')
topics_list= client.list_topics()
print(topics_list)

{'Topics': [{'TopicArn': 'arn:aws:sns:us-west-2:105806319240:MetricAlertSNSTopic'}], 'ResponseMetadata': {'RequestId': '154eb8cf-5305-5e8b-a289-da6abbabb320', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '154eb8cf-5305-5e8b-a289-da6abbabb320', 'date': 'Fri, 12 Jun 2026 10:58:54 GMT', 'content-type': 'text/xml', 'content-length': '384', 'connection': 'keep-alive'}, 'RetryAttempts': 0}}

Next, set the **sns_notifications_topic** variable with the topic ARN value you found in the prior cell.

In [18]:
#set-variables
topic_details = pd.json_normalize(topics_list['Topics'])
topic_arn = topic_details['TopicArn']
print (topic_arn[0])
sns_notifications_topic = topic_arn[0]

arn:aws:sns:us-west-2:105806319240:MetricAlertSNSTopic

Finally, create an alarm using **put_metric_alarm** that triggers a notification when the feature diameter drifts away from the baseline and retrain the model automatically. 

You use the built-in SageMaker AI Model Monitor container for CloudWatch metrics. SageMaker AI emits the metrics for each feature observed in the dataset in the */aws/sagemaker/Endpoints/data-metric* namespace with *EndpointName* and *ScheduleName* dimensions

In [19]:
#trigger-cloudwatch-alarm-when-it-drifts-from-baseline
cw_client = boto3.Session().client('cloudwatch')

alarm_name = 'BASELINE_DRIFT_FEATURE_DIAMETER'
alarm_desc = 'Trigger a CloudWatch alarm when the feature diameter drifts away from the baseline'
feature_diameter_drift_threshold = 0.1  # Setting this threshold purposefully low to see the alarm quickly.
metric_name = 'feature_baseline_drift_diameter'
namespace = 'aws/sagemaker/Endpoints/data-metrics'

cw_client.put_metric_alarm(
    AlarmName=alarm_name,
    AlarmDescription=alarm_desc,
    ActionsEnabled=True,
    AlarmActions=[sns_notifications_topic],
    MetricName=metric_name,
    Namespace=namespace,
    Statistic='Sum',
    Dimensions=[
        {
            'Name': 'Endpoint',
            'Value': endpoint_name
        },
        {
            'Name': 'MonitoringSchedule',
            'Value': mon_schedule_name
        }
    ],
    Period=600,
    EvaluationPeriods=1,
    DatapointsToAlarm=1,
    Threshold=feature_diameter_drift_threshold,
    ComparisonOperator='GreaterThanOrEqualToThreshold',
    TreatMissingData='breaching'
)

{'ResponseMetadata': {'RequestId': '71c3e400-f5cf-484d-a5ce-2275d4a08d68',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '71c3e400-f5cf-484d-a5ce-2275d4a08d68',
   'content-type': 'application/x-amz-json-1.0',
   'content-length': '0',
   'date': 'Fri, 12 Jun 2026 10:59:02 GMT'},
  'RetryAttempts': 0}}

You created a CloudWatch alarm. You can use this alarm to notify you of any data drift issues and trigger automatic model retraining. However, this alarm is set to become an alert state immediately after creation.

## Continue to Task 3

You have completed this notebook. To move to the next part of the lab, do the following:

- Close this notebook file.
- Return to the lab session and continue with **Task 3**.